// packages/vue/src/components/HoverCard/HoverCardContent.vue
<!-- Teleported, positioned surface holding the preview content. -->
<script setup lang="ts">
import { watchEffect } from "vue";
import { HoverCard as ArkHoverCard } from "@ark-ui/vue";
import { useAnchoredPositioning, toPlacement } from "../Popover/positioning.js";
import type { HoverCardContentProps } from "./HoverCard.types.js";

defineOptions({ inheritAttrs: false });
const props = withDefaults(defineProps<HoverCardContentProps>(), {
  side: "bottom",
  align: "center",
  sideOffset: 8,
});

const positioning = useAnchoredPositioning();
// Kept in a watchEffect rather than written once, so a later change to
// side/align/sideOffset reaches the Root — see ../Popover/positioning.ts.
watchEffect(() => {
  if (!positioning) return;
  positioning.value = {
    placement: toPlacement(props.side, props.align),
    gutter: props.sideOffset,
    offset: props.alignOffset != null ? { crossAxis: props.alignOffset } : undefined,
  };
});
</script>

<template>
  <Teleport :to="container ?? 'body'">
    <ArkHoverCard.Positioner class="hover-card__positioner">
      <ArkHoverCard.Content class="hover-card__popup text-default-body-medium" v-bind="$attrs">
        <slot />
      </ArkHoverCard.Content>
    </ArkHoverCard.Positioner>
  </Teleport>
</template>

// packages/svelte/src/lib/components/HoverCard/HoverCardContent.svelte
<!-- Portalled, positioned surface holding the preview content. -->
<script lang="ts">
  import { HoverCard as ArkHoverCard, Portal } from "@ark-ui/svelte";
  import { clsx } from "clsx";
  import { setAnchoredPositioning, toPlacement } from "../Popover/positioning.svelte.js";
  import type { HoverCardContentProps } from "./HoverCard.types.js";

  let {
    side = "bottom",
    align = "center",
    sideOffset = 8,
    alignOffset,
    container,
    class: className,
    children,
    ...contentProps
  }: HoverCardContentProps = $props();

  // Registered with the Root during initialisation, as an accessor so a later
  // change to side/align/sideOffset is picked up — see
  // ../Popover/positioning.svelte.ts.
  setAnchoredPositioning(() => ({
    placement: toPlacement(side, align),
    gutter: sideOffset,
    offset: alignOffset != null ? { crossAxis: alignOffset } : undefined,
  }));
</script>

<Portal container={container ?? undefined}>
  <!--
    The positioner class must stay a plain string literal: the overlay-stacking
    test scans for it, and stacking is declared on the popup rather than here
    because zag writes an inline z-index onto the positioner and reads it from
    the popup's rule.
  -->
  <ArkHoverCard.Positioner class="hover-card__positioner">
    <ArkHoverCard.Content
      class={clsx("hover-card__popup", "text-default-body-medium", className)}
      {...contentProps}
    >
      {@render children?.()}
    </ArkHoverCard.Content>
  </ArkHoverCard.Positioner>
</Portal>
