// packages/vue/src/components/Clipboard/Clipboard.vue
<script setup lang="ts">
import { computed, useAttrs } from "vue";
import { Clipboard as ArkClipboard } from "@ark-ui/vue";
import { clsx } from "clsx";
import { CONTROL_ICON_SIZE, clipboardStyles } from "@ui-organized/core";
import Button from "../Button/Button.vue";
import Icon from "../Icon/Icon.vue";
import type { ClipboardProps } from "./Clipboard.types.js";
import "@ui-organized/core/components/Clipboard/Clipboard.css";

defineOptions({ inheritAttrs: false });
const props = withDefaults(defineProps<ClipboardProps>(), {
  variant: "input",
  size: "md",
  copyLabel: "Copy",
  copiedLabel: "Copied",
});
const emit = defineEmits<{ statusChange: [copied: boolean] }>();

const attrs = useAttrs();
const iconSize = computed(() => CONTROL_ICON_SIZE[props.size]);
const rootClass = computed(() =>
  clsx(
    clipboardStyles({ size: props.size, variant: props.variant }),
    attrs.class as string,
  ),
);

/**
 * Ark Vue calls the copied text `modelValue`, not `value`.
 *
 * Its single-value props are named for `v-model`, so `:value="..."` would be an
 * unknown attribute on the root div and the machine would copy an empty string.
 * The facade keeps `value` so the API matches React and Svelte, and translates
 * here — the same rename Progress needs.
 */
const arkValue = computed(() => props.value);

// Written here rather than inline: a Vue template expression cannot carry an
// object type annotation, and the handler's details argument needs one.
function onStatusChange(details: { copied: boolean }) {
  emit("statusChange", details.copied);
}
</script>

<template>
  <ArkClipboard.Root
    :class="rootClass"
    :model-value="arkValue"
    :timeout="timeout"
    @status-change="onStatusChange"
  >
    <ArkClipboard.Label v-if="label" class="field__label">{{ label }}</ArkClipboard.Label>
    <ArkClipboard.Control class="clipboard__control">
      <ArkClipboard.Input v-if="variant === 'input'" class="clipboard__input" />
      <!--
        The trigger *is* the library Button: Ark hands its props to whatever the
        `as-child` slot renders, so the copy control inherits every interactive
        token instead of restating them.
      -->
      <ArkClipboard.Trigger as-child>
        <Button intent="secondary" :size="size" type="button">
          <!--
            The trigger swaps both its icon and its label on copy. Indicator
            renders its `copied` slot in the copied state and its own children
            otherwise, so the swap costs no local state. The icon goes through an
            Indicator rather than the Button's `icon` prop because only the
            Indicator knows the state.
          -->
          <ArkClipboard.Indicator class="clipboard__indicator">
            <template #copied><Icon name="check" :size="iconSize" /></template>
            <Icon name="copy" :size="iconSize" />
          </ArkClipboard.Indicator>
          <ArkClipboard.Indicator>
            <template #copied>{{ copiedLabel }}</template>
            {{ copyLabel }}
          </ArkClipboard.Indicator>
        </Button>
      </ArkClipboard.Trigger>
    </ArkClipboard.Control>
    <span v-if="helperText" class="field__description">{{ helperText }}</span>
  </ArkClipboard.Root>
</template>

// packages/svelte/src/lib/components/Clipboard/Clipboard.svelte
<script lang="ts">
  import { Clipboard as ArkClipboard } from "@ark-ui/svelte";
  import { clsx } from "clsx";
  import { CONTROL_ICON_SIZE, clipboardStyles } from "@ui-organized/core";
  import Button from "../Button/Button.svelte";
  import Icon from "../Icon/Icon.svelte";
  import type { ClipboardProps } from "./Clipboard.types.js";
  import "@ui-organized/core/components/Clipboard/Clipboard.css";

  let {
    value,
    label,
    helperText,
    variant = "input",
    size = "md",
    copyLabel = "Copy",
    copiedLabel = "Copied",
    timeout,
    onStatusChange,
    class: className,
  }: ClipboardProps = $props();

  const iconSize = $derived(CONTROL_ICON_SIZE[size]);
</script>

<ArkClipboard.Root
  class={clsx(clipboardStyles({ size, variant }), className)}
  {value}
  {timeout}
  onStatusChange={onStatusChange && ((details) => onStatusChange(details.copied))}
>
  {#if label}
    <ArkClipboard.Label class="field__label">{label}</ArkClipboard.Label>
  {/if}
  <ArkClipboard.Control class="clipboard__control">
    {#if variant === "input"}
      <ArkClipboard.Input class="clipboard__input" />
    {/if}
    <!--
      The trigger *is* the library Button: Ark hands its props to whatever the
      asChild snippet renders, so the copy control inherits every interactive
      token instead of restating them.
    -->
    <ArkClipboard.Trigger>
      {#snippet asChild(props)}
        <!--
          `class` is pulled out and handed over separately: Ark types the
          projected props in Svelte's own shapes, where it is a `ClassValue` that
          may be null, while the Button takes a string. Passing it through clsx
          merges it the way Ark's React `asChild` does, rather than dropping a
          class the Trigger might one day carry.
        -->
        {@const { class: arkClass, ...triggerProps } = props()}
        <Button intent="secondary" {size} class={clsx(arkClass)} {...triggerProps}>
          {#snippet children()}
            <!--
              The trigger swaps both its icon and its label on copy. Indicator
              renders its `copied` snippet in the copied state and its own
              children otherwise, so the swap costs no local state. The icon goes
              through an Indicator rather than the Button's `icon` prop because
              only the Indicator knows the state.
            -->
            <ArkClipboard.Indicator class="clipboard__indicator">
              {#snippet copied()}<Icon name="check" size={iconSize} />{/snippet}
              <Icon name="copy" size={iconSize} />
            </ArkClipboard.Indicator>
            <ArkClipboard.Indicator>
              {#snippet copied()}{copiedLabel}{/snippet}
              {copyLabel}
            </ArkClipboard.Indicator>
          {/snippet}
        </Button>
      {/snippet}
    </ArkClipboard.Trigger>
  </ArkClipboard.Control>
  {#if helperText}
    <span class="field__description">{helperText}</span>
  {/if}
</ArkClipboard.Root>
