// packages/react/src/components/Editable/Editable.tsx
import { Editable as ArkEditable } from "@ark-ui/react";
import { clsx } from "clsx";
import { Button } from "../Button/index.js";
import { FieldError } from "../FieldError/index.js";
import { editableStyles } from "@ui-organized/core";
import type { EditableProps } from "./Editable.types.js";
import "@ui-organized/core/components/Editable/Editable.css";

export function Editable({
  label,
  helperText,
  error,
  value,
  defaultValue,
  onValueChange,
  onValueCommit,
  placeholder,
  size = "md",
  activationMode,
  submitMode,
  showControls = false,
  autoResize,
  maxLength,
  required,
  disabled,
  readOnly,
  name,
  className,
}: EditableProps) {
  const isInvalid = !!error;
  const errorMessage = typeof error === "string" ? error : undefined;

  return (
    <ArkEditable.Root
      className={clsx(editableStyles({ size }), className)}
      value={value}
      defaultValue={defaultValue}
      onValueChange={onValueChange && ((details) => onValueChange(details.value))}
      onValueCommit={onValueCommit && ((details) => onValueCommit(details.value))}
      placeholder={placeholder}
      activationMode={activationMode}
      submitMode={submitMode}
      autoResize={autoResize}
      maxLength={maxLength}
      invalid={isInvalid}
      required={required}
      disabled={disabled}
      readOnly={readOnly}
      name={name}
    >
      {label && (
        <ArkEditable.Label className="field__label">
          {label}
          {required && <span className="field__required" aria-hidden="true" />}
        </ArkEditable.Label>
      )}
      <ArkEditable.Area className="editable__area">
        <ArkEditable.Preview className="editable__preview" />
        <ArkEditable.Input className="editable__input" />
      </ArkEditable.Area>
      {/* Ark keeps the edit trigger and the submit/cancel pair mounted in
          opposite states, so the row swaps without any local state here. */}
      {showControls && (
        <ArkEditable.Control className="editable__control">
          <ArkEditable.EditTrigger asChild>
            <Button intent="ghost" size={size} type="button">
              Edit
            </Button>
          </ArkEditable.EditTrigger>
          <ArkEditable.SubmitTrigger asChild>
            <Button intent="secondary" size={size} type="button">
              Save
            </Button>
          </ArkEditable.SubmitTrigger>
          <ArkEditable.CancelTrigger asChild>
            <Button intent="ghost" size={size} type="button">
              Cancel
            </Button>
          </ArkEditable.CancelTrigger>
        </ArkEditable.Control>
      )}
      {helperText && !isInvalid && <span className="field__description">{helperText}</span>}
      {isInvalid && errorMessage && <FieldError>{errorMessage}</FieldError>}
    </ArkEditable.Root>
  );
}

// packages/svelte/src/lib/components/Editable/Editable.svelte
<script lang="ts">
  import { Editable as ArkEditable } from "@ark-ui/svelte";
  import { clsx } from "clsx";
  import { editableStyles } from "@ui-organized/core";
  import Button from "../Button/Button.svelte";
  import FieldError from "../FieldError/FieldError.svelte";
  import type { EditableProps } from "./Editable.types.js";
  import "@ui-organized/core/components/Editable/Editable.css";

  let {
    label,
    helperText,
    error,
    value = $bindable(),
    defaultValue,
    onValueChange,
    onValueCommit,
    placeholder,
    size = "md",
    activationMode,
    submitMode,
    showControls = false,
    autoResize,
    maxLength,
    required,
    disabled,
    readOnly,
    name,
    class: className,
  }: EditableProps = $props();

  const isInvalid = $derived(!!error);
  const errorMessage = $derived(typeof error === "string" ? error : undefined);
</script>

<ArkEditable.Root
  class={clsx(editableStyles({ size }), className)}
  {value}
  {defaultValue}
  onValueChange={(details) => {
    value = details.value;
    onValueChange?.(details.value);
  }}
  onValueCommit={onValueCommit && ((details) => onValueCommit(details.value))}
  {placeholder}
  {activationMode}
  {submitMode}
  {autoResize}
  {maxLength}
  invalid={isInvalid}
  {required}
  {disabled}
  {readOnly}
  {name}
>
  {#if label}
    <ArkEditable.Label class="field__label">
      {label}
      {#if required}<span class="field__required" aria-hidden="true"></span>{/if}
    </ArkEditable.Label>
  {/if}
  <ArkEditable.Area class="editable__area">
    <ArkEditable.Preview class="editable__preview" />
    <ArkEditable.Input class="editable__input" />
  </ArkEditable.Area>
  <!--
    Ark keeps the edit trigger and the submit/cancel pair mounted in opposite
    states, so the row swaps without any local state here.

    Each trigger *is* the library Button, projected through Ark's asChild. `class`
    is pulled out and handed over separately because Ark types the projected props
    in Svelte's own shapes, where it is a `ClassValue` that may be null while the
    Button takes a string — same reason Clipboard's trigger does it.
  -->
  {#if showControls}
    <ArkEditable.Control class="editable__control">
      <ArkEditable.EditTrigger>
        {#snippet asChild(props)}
          {@const { class: arkClass, ...triggerProps } = props()}
          <Button intent="ghost" {size} type="button" class={clsx(arkClass)} {...triggerProps}>
            Edit
          </Button>
        {/snippet}
      </ArkEditable.EditTrigger>
      <ArkEditable.SubmitTrigger>
        {#snippet asChild(props)}
          {@const { class: arkClass, ...triggerProps } = props()}
          <Button intent="secondary" {size} type="button" class={clsx(arkClass)} {...triggerProps}>
            Save
          </Button>
        {/snippet}
      </ArkEditable.SubmitTrigger>
      <ArkEditable.CancelTrigger>
        {#snippet asChild(props)}
          {@const { class: arkClass, ...triggerProps } = props()}
          <Button intent="ghost" {size} type="button" class={clsx(arkClass)} {...triggerProps}>
            Cancel
          </Button>
        {/snippet}
      </ArkEditable.CancelTrigger>
    </ArkEditable.Control>
  {/if}
  {#if helperText && !isInvalid}
    <span class="field__description">{helperText}</span>
  {/if}
  {#if isInvalid && errorMessage}
    <FieldError message={errorMessage} />
  {/if}
</ArkEditable.Root>
