// packages/svelte/src/lib/components/HoverCard/HoverCard.svelte
<!-- HoverCard root — opens a rich preview when the trigger is hovered or focused. -->
<script lang="ts">
  import { HoverCard as ArkHoverCard } from "@ark-ui/svelte";
  import { providePositioning } from "../Popover/positioning.svelte.js";
  import type { HoverCardProps } from "./HoverCard.types.js";
  import "@ui-organized/core/components/HoverCard/HoverCard.css";

  let {
    open = $bindable(),
    defaultOpen,
    onOpenChange,
    openDelay,
    closeDelay,
    children,
  }: HoverCardProps = $props();

  // The Content writes its side/align into this during its own initialisation.
  const positioning = providePositioning({ placement: "bottom", gutter: 8 });
</script>

<ArkHoverCard.Root
  bind:open
  {defaultOpen}
  onOpenChange={(details) => {
    open = details.open;
    onOpenChange?.(details.open);
  }}
  {openDelay}
  {closeDelay}
  positioning={positioning.read()}
>
  {@render children?.()}
</ArkHoverCard.Root>

// packages/react/src/components/HoverCard/HoverCard.tsx
import * as React from "react";
import { HoverCard as ArkHoverCard, Portal } from "@ark-ui/react";
import { clsx } from "clsx";
import type {
  HoverCardProps,
  HoverCardTriggerProps,
  HoverCardContentProps,
} from "./HoverCard.types.js";
import "@ui-organized/core/components/HoverCard/HoverCard.css";
import { projectRender } from "../../utils/projectRender.js";
import { useContainedPositioning, useOverlayPortal } from "../../preview/useOverlayPortal.js";

type Positioning = NonNullable<React.ComponentProps<typeof ArkHoverCard.Root>["positioning"]>;

// Ark sets placement on the Root; the facade keeps side/align on the content, so
// bridge positioning up via context (see Popover for the same pattern).
const SetPositioningContext = React.createContext<((p: Positioning) => void) | null>(null);

/** HoverCard root — opens a rich preview when the trigger is hovered or focused. */
export function HoverCard({
  open,
  defaultOpen,
  onOpenChange,
  openDelay,
  closeDelay,
  children,
}: HoverCardProps) {
  const [positioning, setPositioning] = React.useState<Positioning>({
    placement: "bottom",
    gutter: 8,
  });
  const containedPositioning = useContainedPositioning();
  return (
    <SetPositioningContext.Provider value={setPositioning}>
      <ArkHoverCard.Root
        open={open}
        defaultOpen={defaultOpen}
        onOpenChange={onOpenChange ? (details) => onOpenChange(details.open) : undefined}
        openDelay={openDelay}
        closeDelay={closeDelay}
        positioning={{ ...positioning, ...containedPositioning }}
      >
        {children}
      </ArkHoverCard.Root>
    </SetPositioningContext.Provider>
  );
}

/** The element that reveals the card on hover/focus. */
export function HoverCardTrigger({ render, children, ...props }: HoverCardTriggerProps) {
  if (render) {
    return (
      <ArkHoverCard.Trigger asChild {...props}>
        {projectRender(render, children, "HoverCardTrigger")}
      </ArkHoverCard.Trigger>
    );
  }
  return <ArkHoverCard.Trigger {...props}>{children}</ArkHoverCard.Trigger>;
}

/** Portalled, positioned surface holding the preview content. */
export function HoverCardContent({
  side = "bottom",
  align = "center",
  sideOffset = 8,
  alignOffset,
  container,
  className,
  children,
  ...contentProps
}: HoverCardContentProps) {
  const setPositioning = React.useContext(SetPositioningContext);
  const placement = align === "center" ? side : (`${side}-${align}` as const);
  React.useLayoutEffect(() => {
    setPositioning?.({
      placement,
      gutter: sideOffset,
      offset: alignOffset != null ? { crossAxis: alignOffset } : undefined,
    });
  }, [setPositioning, placement, sideOffset, alignOffset]);

  const portal = useOverlayPortal(container);
  return (
    <Portal {...portal}>
      <ArkHoverCard.Positioner className="hover-card__positioner">
        <ArkHoverCard.Content className={clsx("hover-card__popup", "text-default-body-medium", className)} {...contentProps}>
          {children}
        </ArkHoverCard.Content>
      </ArkHoverCard.Positioner>
    </Portal>
  );
}
