// packages/vue/src/components/Popover/Popover.vue
<!-- Popover root — controls open state. Wrap a trigger and content. -->
<script setup lang="ts">
import { Popover as ArkPopover } from "@ark-ui/vue";
import { definedOnly } from "../../props.js";
import { providePositioning } from "./positioning.js";
import type { PopoverProps } from "./Popover.types.js";
import { computed } from "vue";
import "@ui-organized/core/components/Popover/Popover.css";

const props = defineProps<PopoverProps>();
const emit = defineEmits<{ "update:open": [open: boolean]; openChange: [open: boolean] }>();

// The Content writes its side/align into this.
const positioning = providePositioning({ placement: "bottom", gutter: 8 });

const rootProps = computed(() =>
  definedOnly({ open: props.open, defaultOpen: props.defaultOpen, modal: props.modal }),
);
</script>

<template>
  <ArkPopover.Root
    v-bind="rootProps"
    :positioning="positioning"
    @open-change="
      (details) => {
        emit('update:open', details.open);
        emit('openChange', details.open);
      }
    "
  >
    <slot />
  </ArkPopover.Root>
</template>

// packages/svelte/src/lib/components/Popover/Popover.svelte
<!-- Popover root — controls open state. Wrap a trigger and content. -->
<script lang="ts">
  import { Popover as ArkPopover } from "@ark-ui/svelte";
  import { providePositioning } from "./positioning.svelte.js";
  import type { PopoverProps } from "./Popover.types.js";
  import "@ui-organized/core/components/Popover/Popover.css";

  let {
    open = $bindable(),
    defaultOpen,
    onOpenChange,
    modal,
    children,
  }: PopoverProps = $props();

  // The Content writes its side/align into this during its own initialisation.
  const positioning = providePositioning({ placement: "bottom", gutter: 8 });
</script>

<ArkPopover.Root
  bind:open
  {defaultOpen}
  onOpenChange={(details) => {
    open = details.open;
    onOpenChange?.(details.open);
  }}
  {modal}
  positioning={positioning.read()}
>
  {@render children?.()}
</ArkPopover.Root>
