// packages/react/src/components/Splitter/Splitter.tsx
import { useMemo, Fragment } from "react";
import { Splitter as ArkSplitter } from "@ark-ui/react";
import { clsx } from "clsx";
import { splitterStyles } from "@ui-organized/core";
import type { SplitterProps } from "./Splitter.types.js";
import "@ui-organized/core/components/Splitter/Splitter.css";

export function Splitter({
  panels,
  size,
  defaultSize,
  onResize,
  onResizeEnd,
  orientation = "horizontal",
  variant,
  className,
}: SplitterProps) {
  /* The machine takes its own panel descriptors, not our render data — strip
     `content` so a changed React node never looks like a changed constraint. */
  const panelData = useMemo(
    () =>
      panels.map(({ id, minSize, maxSize, collapsible, collapsedSize }) => ({
        id,
        minSize,
        maxSize,
        collapsible,
        collapsedSize,
      })),
    [panels],
  );

  return (
    <ArkSplitter.Root
      className={clsx(splitterStyles({ orientation, variant }), className)}
      panels={panelData}
      size={size}
      defaultSize={defaultSize}
      onResize={onResize && ((details) => onResize(details.size))}
      onResizeEnd={onResizeEnd && ((details) => onResizeEnd(details.size))}
      orientation={orientation}
    >
      {panels.map((panel, index) => (
        <Fragment key={panel.id}>
          <ArkSplitter.Panel id={panel.id} className="splitter__panel">
            {panel.content}
          </ArkSplitter.Panel>
          {/* A handle sits between adjacent panels, so the last panel has none.
              zag identifies it by the literal "before:after" pair of ids. */}
          {index < panels.length - 1 && (
            <ArkSplitter.ResizeTrigger
              id={`${panel.id}:${panels[index + 1]!.id}`}
              className="splitter__trigger"
              // The handle is a <button role="separator"> whose only child is a
              // decorative grip, so it had no accessible name — a keyboard user
              // landed on an unnamed control with arrow keys that did something
              // unexplained. Naming it after the two panels it sits between says
              // what moving it will do.
              aria-label={`Resize ${panel.label ?? panel.id} and ${
                panels[index + 1]!.label ?? panels[index + 1]!.id
              }`}
            >
              <span className="splitter__grip" aria-hidden="true" />
            </ArkSplitter.ResizeTrigger>
          )}
        </Fragment>
      ))}
    </ArkSplitter.Root>
  );
}

// packages/svelte/src/lib/components/Splitter/Splitter.svelte
<script lang="ts">
  import { Splitter as ArkSplitter } from "@ark-ui/svelte";
  import { clsx } from "clsx";
  import { splitterStyles } from "@ui-organized/core";
  import type { SplitterProps } from "./Splitter.types.js";
  import "@ui-organized/core/components/Splitter/Splitter.css";

  let {
    panels,
    size = $bindable(),
    defaultSize,
    onResize,
    onResizeEnd,
    orientation = "horizontal",
    variant,
    class: className,
  }: SplitterProps = $props();

  /* The machine takes its own panel descriptors, not our render data — strip
     `content` so a changed snippet never looks like a changed constraint. */
  const panelData = $derived(
    panels.map(({ id, minSize, maxSize, collapsible, collapsedSize }) => ({
      id,
      minSize,
      maxSize,
      collapsible,
      collapsedSize,
    })),
  );
</script>

<!--
  `bind:size` rather than a plain prop: Ark's own Root declares `size` bindable
  and writes the new layout back on every resize, so binding is what keeps an
  uncontrolled splitter's `bind:size` reading the sizes the user dragged to.
-->
<ArkSplitter.Root
  class={clsx(splitterStyles({ orientation, variant }), className)}
  panels={panelData}
  bind:size
  {defaultSize}
  onResize={onResize && ((details) => onResize(details.size))}
  onResizeEnd={onResizeEnd && ((details) => onResizeEnd(details.size))}
  {orientation}
>
  {#each panels as panel, index (panel.id)}
    <ArkSplitter.Panel id={panel.id} class="splitter__panel">
      {#if typeof panel.content === "string"}{panel.content}{:else}{@render panel.content?.()}{/if}
    </ArkSplitter.Panel>
    <!--
      A handle sits between adjacent panels, so the last panel has none.
      zag identifies it by the literal "before:after" pair of ids.
    -->
    {#if index < panels.length - 1}
      <!-- The handle is a <button role="separator"> whose only child is a
           decorative grip, so it had no accessible name — a keyboard user landed
           on an unnamed control with arrow keys that did something unexplained.
           Naming it after the two panels it sits between says what moving it
           will do. Same name as the React library's. -->
      <ArkSplitter.ResizeTrigger
        id={`${panel.id}:${panels[index + 1]!.id}`}
        class="splitter__trigger"
        aria-label={`Resize ${panel.label ?? panel.id} and ${
          panels[index + 1]!.label ?? panels[index + 1]!.id
        }`}
      >
        <span class="splitter__grip" aria-hidden="true"></span>
      </ArkSplitter.ResizeTrigger>
    {/if}
  {/each}
</ArkSplitter.Root>
