// packages/react/src/components/SearchInput/SearchInput.tsx
import { useEffect, useRef, useState, type ChangeEvent } from "react";
import { Field } from "@ark-ui/react";
import { clsx } from "clsx";
import { CONTROL_ICON_SIZE, searchInputFieldStyles } from "@ui-organized/core";
import { Icon } from "../Icon/index.js";
import { FieldError } from "../FieldError/index.js";
import type { SearchInputProps } from "./SearchInput.types.js";
// Shares the Input field surface/state styling; InputAffix.css layers on the
// leading icon and clear button.
import "@ui-organized/core/components/Input/Input.css";
import "@ui-organized/core/components/Input/InputAffix.css";

export function SearchInput({
  label,
  helperText,
  error,
  size,
  required,
  clearable = true,
  onClear,
  className,
  value,
  defaultValue,
  disabled,
  onChange,
  ...inputProps
}: SearchInputProps) {
  const isInvalid = !!error;
  const errorMessage = typeof error === "string" ? error : undefined;

  const inputRef = useRef<HTMLInputElement>(null);
  const isControlled = value !== undefined;
  const [hasValue, setHasValue] = useState(
    () => String((isControlled ? value : defaultValue) ?? "").length > 0,
  );

  // Keep the clear button in sync when the value is driven from the outside.
  useEffect(() => {
    if (isControlled) setHasValue(String(value ?? "").length > 0);
  }, [isControlled, value]);

  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
    if (!isControlled) setHasValue(event.target.value.length > 0);
    onChange?.(event);
  };

  const handleClear = () => {
    const input = inputRef.current;
    if (input) {
      // Clear through the native value setter and dispatch an input event so
      // React's onChange fires for both controlled and uncontrolled usage.
      const setNativeValue = Object.getOwnPropertyDescriptor(
        window.HTMLInputElement.prototype,
        "value",
      )?.set;
      setNativeValue?.call(input, "");
      input.dispatchEvent(new Event("input", { bubbles: true }));
      input.focus();
    }
    if (!isControlled) setHasValue(false);
    onClear?.();
  };

  const showClear = clearable && hasValue && !disabled;

  return (
    <Field.Root
      className={clsx(searchInputFieldStyles({ size }), className)}
      invalid={isInvalid}
    >
      {label && (
        <Field.Label className="field__label">
          {label}
          {required && <span className="field__required" aria-hidden="true" />}
        </Field.Label>
      )}
      <div className="input-affix">
        <span
          className="input-affix__adornment input-affix__adornment--start"
          aria-hidden="true"
        >
          <Icon name="search" size={CONTROL_ICON_SIZE[size ?? "md"]} />
        </span>
        <Field.Input
          ref={inputRef}
          type="search"
          className={clsx(
            "field__control",
            "field__control--affix-start",
            showClear && "field__control--affix-end",
          )}
          required={required}
          disabled={disabled}
          value={value}
          defaultValue={defaultValue}
          onChange={handleChange}
          {...inputProps}
        />
        {showClear && (
          <button
            type="button"
            className="input-affix__adornment input-affix__adornment--end input-affix__action"
            onClick={handleClear}
            aria-label="Clear search"
            tabIndex={-1}
          >
            <Icon name="close" size={CONTROL_ICON_SIZE[size ?? "md"]} />
          </button>
        )}
      </div>
      {helperText && !isInvalid && (
        <Field.HelperText className="field__description">
          {helperText}
        </Field.HelperText>
      )}
      {isInvalid && errorMessage && (
        <Field.ErrorText asChild>
          <FieldError>{errorMessage}</FieldError>
        </Field.ErrorText>
      )}
    </Field.Root>
  );
}

// packages/svelte/src/lib/components/SearchInput/SearchInput.svelte
<script lang="ts">
  import { Field } from "@ark-ui/svelte";
  import { clsx } from "clsx";
  import { CONTROL_ICON_SIZE, searchInputFieldStyles } from "@ui-organized/core";
  import Icon from "../Icon/Icon.svelte";
  import FieldError from "../FieldError/FieldError.svelte";
  import type { SearchInputProps } from "./SearchInput.types.js";
  // Shares the Input field surface/state styling; InputAffix.css layers on the
  // leading icon and clear button.
  import "@ui-organized/core/components/Input/Input.css";
  import "@ui-organized/core/components/Input/InputAffix.css";

  let {
    label,
    helperText,
    error,
    size,
    required,
    clearable = true,
    onClear,
    class: className,
    value = $bindable(),
    defaultValue,
    disabled,
    ...inputProps
  }: SearchInputProps = $props();

  const isInvalid = $derived(!!error);
  const errorMessage = $derived(typeof error === "string" ? error : undefined);

  let inputEl = $state<HTMLInputElement | null>(null);

  // React has to mirror the value into state and re-sync it from an effect,
  // because a controlled input's value lives outside the component. `bind:value`
  // puts it here whether or not the consumer binds as well, so the clear button
  // can just be derived — no second copy to keep in step.
  const hasValue = $derived(String((value ?? defaultValue) ?? "").length > 0);
  const showClear = $derived(clearable && hasValue && !disabled);

  function clear() {
    if (inputEl) {
      // Assigning `.value` fires no event, so a consumer listening on `oninput`
      // rather than binding would never learn the field was cleared.
      inputEl.value = "";
      inputEl.dispatchEvent(new Event("input", { bubbles: true }));
      inputEl.focus();
    }
    value = "";
    onClear?.();
  }
</script>

<Field.Root class={clsx(searchInputFieldStyles({ size }), className)} invalid={isInvalid}>
  {#if label}
    <Field.Label class="field__label">
      {label}
      {#if required}<span class="field__required" aria-hidden="true"></span>{/if}
    </Field.Label>
  {/if}
  <div class="input-affix">
    <span class="input-affix__adornment input-affix__adornment--start" aria-hidden="true">
      <Icon name="search" size={CONTROL_ICON_SIZE[size ?? "md"]} />
    </span>
    <Field.Input
      bind:ref={inputEl}
      type="search"
      class={clsx(
        "field__control",
        "field__control--affix-start",
        showClear && "field__control--affix-end",
      )}
      {required}
      {disabled}
      bind:value
      {defaultValue}
      {...inputProps}
    />
    {#if showClear}
      <!--
        Out of the tab order: the field it clears is the next stop anyway, and a
        control that appears and disappears as you type would otherwise shift the
        tab sequence under the keyboard user mid-word.
      -->
      <button
        type="button"
        class="input-affix__adornment input-affix__adornment--end input-affix__action"
        onclick={clear}
        aria-label="Clear search"
        tabindex={-1}
      >
        <Icon name="close" size={CONTROL_ICON_SIZE[size ?? "md"]} />
      </button>
    {/if}
  </div>
  {#if helperText && !isInvalid}
    <Field.HelperText class="field__description">{helperText}</Field.HelperText>
  {/if}
  {#if isInvalid && errorMessage}
    <Field.ErrorText>
      {#snippet asChild(props)}
        <FieldError {...props()} message={errorMessage} />
      {/snippet}
    </Field.ErrorText>
  {/if}
</Field.Root>
