// packages/vue-table/src/components/Table/TableFooter.vue
<script setup lang="ts">
import { computed, useSlots } from "vue";
import { clsx } from "clsx";
import { FlexRender } from "@tanstack/vue-table";
import { useTableContext } from "../../core/tableContext.js";

defineProps<{ class?: string }>();
const slots = useSlots();
const table = useTableContext();

const groups = computed(() => table.table.getFooterGroups());
const hasFooter = computed(() =>
  groups.value.some((group) =>
    group.headers.some((header) => header.column.columnDef.footer !== undefined),
  ),
);
const render = computed(() => Boolean(slots.default) || hasFooter.value);
</script>

<template>
  <tfoot v-if="render" :class="clsx('data-table__foot', $props.class)">
    <slot>
      <tr v-for="group in groups" :key="group.id" class="data-table__row">
        <td v-for="header in group.headers" :key="header.id" class="data-table__cell">
          <FlexRender v-if="!header.isPlaceholder" :footer="header" />
        </td>
      </tr>
    </slot>
  </tfoot>
</template>

// packages/svelte-table/src/lib/components/Table/TableFooter.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { clsx } from "clsx";
  import { FlexRender } from "@tanstack/svelte-table";
  import { getTable } from "../../core/tableContext.js";

  let { class: className, children }: { class?: string; children?: Snippet } = $props();
  const table = getTable();

  const groups = $derived(table.table.getFooterGroups());
  const hasFooter = $derived(
    groups.some((group) =>
      group.headers.some((header) => header.column.columnDef.footer !== undefined),
    ),
  );
</script>

{#if children || hasFooter}
  <tfoot class={clsx("data-table__foot", className)}>
    {#if children}
      {@render children()}
    {:else}
      {#each groups as group (group.id)}
        <tr class="data-table__row">
          {#each group.headers as header (header.id)}
            <td class="data-table__cell">
              {#if !header.isPlaceholder}<FlexRender footer={header} />{/if}
            </td>
          {/each}
        </tr>
      {/each}
    {/if}
  </tfoot>
{/if}
