// packages/svelte/src/lib/components/Breadcrumb/Breadcrumb.svelte
<!--
  A trail of links showing the current page's location in a hierarchy.

  No Ark machine behind it — Ark UI has no Breadcrumb primitive — so the markup
  here is the contract, compared element for element against the React library by
  the parity gate.
-->
<script lang="ts">
  import { clsx } from "clsx";
  import Icon from "../Icon/Icon.svelte";
  import type { BreadcrumbItem, BreadcrumbProps } from "./Breadcrumb.types.js";
  import "@ui-organized/core/components/Breadcrumb/Breadcrumb.css";

  const ICON_SIZE = 16;

  let { items, separator, class: className, ...rest }: BreadcrumbProps = $props();

  const isLast = (index: number) => index === items.length - 1;
</script>

{#snippet crumb(item: BreadcrumbItem)}
  {#if item.icon}
    <Icon name={item.icon} size={ICON_SIZE} class="breadcrumb__icon" />
  {/if}
  {#if typeof item.label === "string"}{item.label}{:else}{@render item.label()}{/if}
{/snippet}

<nav
  aria-label="Breadcrumb"
  class={clsx("breadcrumb", "text-default-body-medium", className)}
  {...rest}
>
  <ol class="breadcrumb__list">
    {#each items as item, index (index)}
      <li class="breadcrumb__item">
        {#if item.href && !isLast(index)}
          <a href={item.href} class="breadcrumb__link">{@render crumb(item)}</a>
        {:else}
          <!--
            The last crumb is the current page even when it carries an href, so it
            renders as text rather than as a link nobody would follow.
          -->
          <span class="breadcrumb__current" aria-current={isLast(index) ? "page" : undefined}>
            {@render crumb(item)}
          </span>
        {/if}
        {#if !isLast(index)}
          <span class="breadcrumb__separator" aria-hidden="true">
            {#if separator == null}
              <Icon name="chevron-right" size={ICON_SIZE} />
            {:else if typeof separator === "string"}{separator}{:else}{@render separator()}{/if}
          </span>
        {/if}
      </li>
    {/each}
  </ol>
</nav>

// packages/react/src/components/Breadcrumb/Breadcrumb.tsx
import { clsx } from "clsx";
import { Icon } from "../Icon/index.js";
import type { BreadcrumbProps } from "./Breadcrumb.types.js";
import "@ui-organized/core/components/Breadcrumb/Breadcrumb.css";

/** A trail of links showing the current page's location in a hierarchy. */
export function Breadcrumb({ items, separator, className, ...props }: BreadcrumbProps) {
  return (
    <nav aria-label="Breadcrumb" className={clsx("breadcrumb", "text-default-body-medium", className)} {...props}>
      <ol className="breadcrumb__list">
        {items.map((item, index) => {
          const isLast = index === items.length - 1;
          return (
            <li key={index} className="breadcrumb__item">
              {item.href && !isLast ? (
                <a href={item.href} className="breadcrumb__link">
                  {item.icon && <Icon name={item.icon} size={16} className="breadcrumb__icon" />}
                  {item.label}
                </a>
              ) : (
                <span
                  className="breadcrumb__current"
                  aria-current={isLast ? "page" : undefined}
                >
                  {item.icon && <Icon name={item.icon} size={16} className="breadcrumb__icon" />}
                  {item.label}
                </span>
              )}
              {!isLast && (
                <span className="breadcrumb__separator" aria-hidden="true">
                  {separator ?? <Icon name="chevron-right" size={16} />}
                </span>
              )}
            </li>
          );
        })}
      </ol>
    </nav>
  );
}
