// packages/svelte/src/lib/components/PasswordInput/PasswordInput.svelte
<script lang="ts">
  import { Field } from "@ark-ui/svelte";
  import { clsx } from "clsx";
  import { CONTROL_ICON_SIZE, passwordInputFieldStyles } from "@ui-organized/core";
  import Icon from "../Icon/Icon.svelte";
  import FieldError from "../FieldError/FieldError.svelte";
  import type { PasswordInputProps } from "./PasswordInput.types.js";
  // Shares the Input field surface/state styling; InputAffix.css layers on the
  // trailing show/hide toggle.
  import "@ui-organized/core/components/Input/Input.css";
  import "@ui-organized/core/components/Input/InputAffix.css";

  let {
    label,
    helperText,
    error,
    size,
    required,
    showToggle = true,
    class: className,
    disabled,
    value = $bindable(),
    ...inputProps
  }: PasswordInputProps = $props();

  const isInvalid = $derived(!!error);
  const errorMessage = $derived(typeof error === "string" ? error : undefined);

  let visible = $state(false);
</script>

<Field.Root class={clsx(passwordInputFieldStyles({ size }), className)} invalid={isInvalid}>
  {#if label}
    <Field.Label class="field__label">
      {label}
      {#if required}<span class="field__required" aria-hidden="true"></span>{/if}
    </Field.Label>
  {/if}
  <div class="input-affix">
    <Field.Input
      type={visible ? "text" : "password"}
      class={clsx("field__control", showToggle && "field__control--affix-end")}
      {required}
      {disabled}
      bind:value
      {...inputProps}
    />
    {#if showToggle}
      <!--
        A plain button rather than a Toggle: it reveals the field rather than
        changing its value, so it stays out of the form's tab-and-submit story
        and is named by what it will do next.
      -->
      <button
        type="button"
        class="input-affix__adornment input-affix__adornment--end input-affix__action"
        onclick={() => (visible = !visible)}
        aria-label={visible ? "Hide password" : "Show password"}
        aria-pressed={visible}
        {disabled}
      >
        <Icon name={visible ? "eye-off" : "eye"} size={CONTROL_ICON_SIZE[size ?? "md"]} />
      </button>
    {/if}
  </div>
  {#if helperText && !isInvalid}
    <Field.HelperText class="field__description">{helperText}</Field.HelperText>
  {/if}
  {#if isInvalid && errorMessage}
    <Field.ErrorText>
      {#snippet asChild(props)}
        <FieldError {...props()} message={errorMessage} />
      {/snippet}
    </Field.ErrorText>
  {/if}
</Field.Root>

// packages/react/src/components/PasswordInput/PasswordInput.tsx
import { useState } from "react";
import { Field } from "@ark-ui/react";
import { clsx } from "clsx";
import { CONTROL_ICON_SIZE, passwordInputFieldStyles } from "@ui-organized/core";
import { Icon } from "../Icon/index.js";
import { FieldError } from "../FieldError/index.js";
import type { PasswordInputProps } from "./PasswordInput.types.js";
// Shares the Input field surface/state styling; InputAffix.css layers on the
// trailing show/hide toggle.
import "@ui-organized/core/components/Input/Input.css";
import "@ui-organized/core/components/Input/InputAffix.css";

export function PasswordInput({
  label,
  helperText,
  error,
  size,
  required,
  showToggle = true,
  className,
  disabled,
  ...inputProps
}: PasswordInputProps) {
  const isInvalid = !!error;
  const errorMessage = typeof error === "string" ? error : undefined;
  const [visible, setVisible] = useState(false);

  return (
    <Field.Root
      className={clsx(passwordInputFieldStyles({ size }), className)}
      invalid={isInvalid}
    >
      {label && (
        <Field.Label className="field__label">
          {label}
          {required && <span className="field__required" aria-hidden="true" />}
        </Field.Label>
      )}
      <div className="input-affix">
        <Field.Input
          type={visible ? "text" : "password"}
          className={clsx(
            "field__control",
            showToggle && "field__control--affix-end",
          )}
          required={required}
          disabled={disabled}
          {...inputProps}
        />
        {showToggle && (
          <button
            type="button"
            className="input-affix__adornment input-affix__adornment--end input-affix__action"
            onClick={() => setVisible((v) => !v)}
            aria-label={visible ? "Hide password" : "Show password"}
            aria-pressed={visible}
            disabled={disabled}
          >
            <Icon name={visible ? "eye-off" : "eye"} size={CONTROL_ICON_SIZE[size ?? "md"]} />
          </button>
        )}
      </div>
      {helperText && !isInvalid && (
        <Field.HelperText className="field__description">
          {helperText}
        </Field.HelperText>
      )}
      {isInvalid && errorMessage && (
        <Field.ErrorText asChild>
          <FieldError>{errorMessage}</FieldError>
        </Field.ErrorText>
      )}
    </Field.Root>
  );
}
