// packages/angular/src/lib/date-range-input/date-range-input.ts
import { NgTemplateOutlet } from "@angular/common";
import {
  AfterViewInit,
  ApplicationRef,
  Component,
  ElementRef,
  ViewChild,
  booleanAttribute,
  computed,
  inject,
  input,
  model,
} from "@angular/core";
import { clsx } from "clsx";
import {
  CONTROL_ICON_SIZE,
  inputFieldStyles,
  parseISODate,
  toISODate,
  type ControlSize,
  type DateRangeInputVariants,
} from "@ui-organized/core";
import { UioCalendar, type CalendarRange } from "../calendar/calendar.js";
import { UioDatePopover, UioDatePopoverTrigger } from "../date-field/date-popover.js";
import { coarsePointer } from "../date-field/coarse-pointer.js";
import { openDatePicker } from "../date-field/open-date-picker.js";
import { UioIcon } from "../icons/icon.js";
import { flushNow } from "../overlay/flush.js";
import { nextMachineId } from "../part-ids.js";

export type DateRangeInputSize = NonNullable<DateRangeInputVariants["size"]>;

/** The paired ends of a range, as ISO `YYYY-MM-DD` strings; `""` when empty. */
export interface DateRangeValue {
  start: string;
  end: string;
}

const EMPTY_RANGE: DateRangeValue = { start: "", end: "" };

/** The icon pill in front of each control, which both ends share. */
const ADORNMENT =
  "input-affix__adornment input-affix__adornment--start input-affix__action";

/**
 * A from–to date range built from two native `<input type="date">` controls on
 * the Input field surface, under one shared label, helper text and error.
 *
 * ```html
 * <div uioDateRangeInput label="Stay" [(value)]="stay" min="2024-01-01"></div>
 * ```
 *
 * On a fine pointer the leading calendar buttons open one shared two-month range
 * calendar; on touch they defer to the OS-native picker. The two ends
 * auto-constrain each other — the end cannot precede the start — on top of the
 * optional `min`/`max`.
 *
 * ── Three things that look like details and are not ─────────────────────────
 *
 * **The root is not a `Field`.** It is a plain `role="group"` naming itself with
 * `aria-labelledby`, because two controls under one label is a group and not a
 * field: a `<label for>` may only name one of them. That is also why the label
 * is a `<span>`, the helper text a `<p>`, and the error pill is written out here
 * rather than being `UioFieldError` — outside a field that component renders no
 * id, and this group needs one to describe itself by.
 *
 * **Only the start button is a popover trigger.** One popover may have one
 * trigger and the range shares a single calendar, so the end button sets the
 * open state by hand. It is the one control in the date family whose behaviour
 * is written rather than delegated.
 *
 * **The row is split across two templates.** The coarse-pointer fork has to
 * bracket the popover as well as the button — a touch device renders no calendar
 * at all — and a template reference cannot cross an `@if`. The two inputs and
 * the separator, which is where all the attributes live, are shared between the
 * branches rather than written twice.
 */
@Component({
  selector: "div[uioDateRangeInput]",
  standalone: true,
  exportAs: "uioDateRangeInput",
  imports: [NgTemplateOutlet, UioCalendar, UioDatePopover, UioDatePopoverTrigger, UioIcon],
  host: {
    role: "group",
    "[class]": "hostClass()",
    "[attr.aria-labelledby]": "label() ? labelId : null",
    "[attr.aria-describedby]": "describedBy()",
    "[attr.data-disabled]": "disabled() ? 'true' : null",
  },
  template: `
    @if (label(); as text) {
      <span class="field__label" [id]="labelId"
        >{{ text }}@if (required()) {<span class="field__required" aria-hidden="true"></span>}</span
      >
    }

    @if (coarse()) {
      <div class="date-range__row" #row>
        <div class="input-affix date-range__field">
          <button
            type="button"
            [class]="ADORNMENT"
            [attr.aria-label]="startPickerLabel()"
            [disabled]="disabled()"
            (click)="onStartPicker()"
          >
            <span uioIcon name="calendar" [size]="iconSize()"></span>
          </button>
          <ng-container [ngTemplateOutlet]="startInput" />
        </div>
        <ng-container [ngTemplateOutlet]="tail" />
      </div>
    } @else {
      <div class="date-range__row" #row>
        <div class="input-affix date-range__field">
          <button
            uioDatePopoverTrigger
            [datePopover]="surface"
            [class]="ADORNMENT"
            [attr.aria-label]="startPickerLabel()"
            [disabled]="disabled()"
          >
            <span uioIcon name="calendar" [size]="iconSize()"></span>
          </button>
          <ng-container [ngTemplateOutlet]="startInput" />
        </div>
        <ng-container [ngTemplateOutlet]="tail" />
      </div>

      <uio-date-popover #surface="uioDatePopover" [label]="popupLabel()">
        <div
          uioCalendar
          mode="range"
          [numMonths]="2"
          [rangeValue]="calendarRange()"
          [min]="calendarMin()"
          [max]="calendarMax()"
          (rangeChange)="onRangeChange($event)"
          (rangeComplete)="surface.hide()"
        ></div>
      </uio-date-popover>
    }

    @if (helperVisible()) {
      <p class="field__description" [id]="helperId">{{ helperText() }}</p>
    }
    @if (errorVisible()) {
      <!--
        The pill UioFieldError renders, written out because this group is not an
        Ark Field: outside one that component emits no id, and no "data-scope"
        or "aria-live" either — which is what React renders here too.
      -->
      <span class="field-error text-emphasis-caption" [id]="errorId"
        ><span uioIcon class="field-error__icon" name="alert-circle" [size]="ERROR_ICON_SIZE"></span
        >{{ errorMessage() }}</span
      >
    }

    <ng-template #startInput>
      <input
        #startControl
        type="date"
        class="field__control field__control--affix-start"
        [attr.data-empty]="current().start ? null : 'true'"
        [attr.min]="min()"
        [attr.max]="current().end || max()"
        [attr.name]="startName()"
        [attr.required]="required() ? '' : null"
        [attr.aria-label]="startLabel()"
        [attr.aria-invalid]="invalid() ? 'true' : null"
        [disabled]="disabled()"
        [value]="current().start"
        (input)="onEndpointInput($event, true)"
      />
    </ng-template>

    <ng-template #tail>
      <span class="date-range__separator text-default-body-large" aria-hidden="true">{{
        separator()
      }}</span>
      <div class="input-affix date-range__field">
        <button
          type="button"
          [class]="ADORNMENT"
          [attr.aria-label]="endPickerLabel()"
          [disabled]="disabled()"
          (click)="onEndPicker()"
        >
          <span uioIcon name="calendar" [size]="iconSize()"></span>
        </button>
        <input
          #endControl
          type="date"
          class="field__control field__control--affix-start"
          [attr.data-empty]="current().end ? null : 'true'"
          [attr.min]="current().start || min()"
          [attr.max]="max()"
          [attr.name]="endName()"
          [attr.required]="required() ? '' : null"
          [attr.aria-label]="endLabel()"
          [attr.aria-invalid]="invalid() ? 'true' : null"
          [disabled]="disabled()"
          [value]="current().end"
          (input)="onEndpointInput($event, false)"
        />
      </div>
    </ng-template>
  `,
})
export class UioDateRangeInput implements AfterViewInit {
  readonly label = input<string | undefined>(undefined);
  readonly helperText = input<string | undefined>(undefined);
  /** A string shows an error message; `true` marks the range invalid without one. */
  readonly error = input<string | boolean | undefined>(undefined);
  readonly size = input<DateRangeInputSize>("md");
  readonly required = input(false, { transform: booleanAttribute });
  readonly disabled = input(false, { transform: booleanAttribute });

  /** Uncontrolled until something binds it — the fork `UioSwitch` describes. */
  readonly value = model<DateRangeValue>(EMPTY_RANGE);

  /** Earliest selectable date for both controls (ISO `YYYY-MM-DD`). */
  readonly min = input<string | undefined>(undefined);
  /** Latest selectable date for both controls (ISO `YYYY-MM-DD`). */
  readonly max = input<string | undefined>(undefined);

  readonly startName = input<string | undefined>(undefined);
  readonly endName = input<string | undefined>(undefined);
  readonly startLabel = input("Start date");
  readonly endLabel = input("End date");
  /** Rendered between the two controls. Defaults to an en dash. */
  readonly separator = input("–");

  private readonly machine = nextMachineId();
  protected readonly labelId = `${this.machine}-label`;
  protected readonly helperId = `${this.machine}-helper`;
  protected readonly errorId = `${this.machine}-error`;

  protected readonly ADORNMENT = ADORNMENT;
  protected readonly ERROR_ICON_SIZE = 12;

  private readonly appRef = inject(ApplicationRef);
  protected readonly coarse = coarsePointer();

  protected readonly invalid = computed(() => !!this.error());
  protected readonly errorMessage = computed(() =>
    typeof this.error() === "string" ? (this.error() as string) : undefined,
  );
  protected readonly helperVisible = computed(() => !!this.helperText() && !this.invalid());
  protected readonly errorVisible = computed(() => this.invalid() && !!this.errorMessage());
  protected readonly describedBy = computed(() => {
    const ids = [
      this.helperVisible() ? this.helperId : null,
      this.errorVisible() ? this.errorId : null,
    ].filter(Boolean);
    return ids.length ? ids.join(" ") : null;
  });

  protected readonly hostClass = computed(() =>
    clsx(inputFieldStyles({ size: this.size() }), "date-range"),
  );
  protected readonly iconSize = computed(() => CONTROL_ICON_SIZE[this.size() as ControlSize]);

  protected readonly current = computed(
    (): DateRangeValue => ({ start: this.value().start ?? "", end: this.value().end ?? "" }),
  );
  protected readonly calendarRange = computed(
    (): CalendarRange => ({
      start: parseISODate(this.current().start),
      end: parseISODate(this.current().end),
    }),
  );
  protected readonly calendarMin = computed(() => parseISODate(this.min()));
  protected readonly calendarMax = computed(() => parseISODate(this.max()));

  protected readonly startPickerLabel = computed(() => `${this.startLabel()} — choose date`);
  protected readonly endPickerLabel = computed(() => `${this.endLabel()} — choose date`);
  protected readonly popupLabel = computed(
    () => `${this.startLabel()} — ${this.endLabel()}, choose dates`,
  );

  @ViewChild("row") private row?: ElementRef<HTMLElement>;
  @ViewChild("startControl") private startControl?: ElementRef<HTMLInputElement>;
  @ViewChild("endControl") private endControl?: ElementRef<HTMLInputElement>;
  @ViewChild(UioCalendar) private calendar?: UioCalendar;
  @ViewChild(UioDatePopover) private popover?: UioDatePopover;

  ngAfterViewInit(): void {
    // The whole row, not the 32px button — the popup belongs to the pair. And
    // opened onto the calendar's active day rather than the "Previous month"
    // button, which is what `focusInside` would otherwise find first.
    this.popover?.anchorTo(this.row?.nativeElement ?? null, null);
    if (this.popover) {
      this.popover.initialFocus = () => this.calendar?.activeDayElement() ?? null;
    }
  }

  protected onStartPicker(): void {
    openDatePicker(this.startControl?.nativeElement ?? null);
  }

  /**
   * The end button, which is a plain button in both modes.
   *
   * On touch it opens the OS picker for its own control; on a fine pointer it
   * opens the shared calendar, because a popover may only have one trigger and
   * the start button already is it.
   */
  protected onEndPicker(): void {
    if (this.coarse()) {
      openDatePicker(this.endControl?.nativeElement ?? null);
      return;
    }
    this.popover?.show();
  }

  protected onEndpointInput(event: Event, isStart: boolean): void {
    const next = (event.target as HTMLInputElement).value;
    const current = this.current();
    this.update(isStart ? { start: next, end: current.end } : { start: current.start, end: next });
  }

  protected onRangeChange(range: CalendarRange): void {
    this.update({
      start: range.start ? toISODate(range.start) : "",
      end: range.end ? toISODate(range.end) : "",
    });
  }

  private update(next: DateRangeValue): void {
    this.value.set(next);
    // Both ends and the calendar's band are refreshed by different views; see
    // `write` in `UioDateFieldBase` for why a discrete interaction flushes.
    flushNow(this.appRef);
  }
}

// packages/vue/src/components/DateRangeInput/DateRangeInput.vue
<!--
  A from–to date range built from two native `<input type="date">` controls on
  the Input field surface, under one shared label, helper text and error.

  On fine pointers the leading calendar buttons open one shared DS-styled
  two-month range calendar; on touch devices they defer to the OS-native picker.
  The two ends auto-constrain each other (the end can't precede the start) on top
  of the optional `min` / `max` bounds. Works with `v-model` or uncontrolled
  (`defaultValue`).
-->
<script setup lang="ts">
import { computed, ref, useAttrs, useId } from "vue";
import { Popover as ArkPopover } from "@ark-ui/vue";
import { clsx } from "clsx";
import {
  CONTROL_ICON_SIZE,
  inputFieldStyles,
  parseISODate,
  popupControls,
  toISODate,
} from "@ui-organized/core";
import { definedOnly } from "../../props.js";
import Icon from "../Icon/Icon.vue";
import FieldError from "../FieldError/FieldError.vue";
import Calendar from "../Calendar/Calendar.vue";
import DatePopover from "../DateField/DatePopover.vue";
import { datePopoverPositioning } from "../DateField/datePopoverPositioning.js";
import { openDatePicker } from "../DateField/openDatePicker.js";
import { useCoarsePointer } from "../DateField/useCoarsePointer.js";
import type { DateRangeInputProps, DateRangeValue } from "./DateRangeInput.types.js";
// Shares the Input field surface/state styling; InputAffix.css supplies the
// leading calendar buttons; DateRangeInput.css lays out the start/end pair.
import "@ui-organized/core/components/Input/Input.css";
import "@ui-organized/core/components/Input/InputAffix.css";
import "@ui-organized/core/components/DateRangeInput/DateRangeInput.css";

type Side = "start" | "end";
const SIDES = ["start", "end"] as const;

defineOptions({ inheritAttrs: false });
// Every boolean forwarded on must default to `undefined`. Vue casts an absent
// Boolean prop to `false`, and neither Ark nor the native control can tell that
// apart from a deliberate one — see ../../props.ts.
const props = withDefaults(defineProps<DateRangeInputProps>(), {
  required: undefined,
  disabled: undefined,
  startLabel: "Start date",
  endLabel: "End date",
  separator: "–",
});
/**
 * `valueChange` rather than `change`, matching Select.
 *
 * A declared `change` emit would swallow a consumer's `@change` — which on a
 * component wrapping two native inputs is a listener they may well have meant
 * for the DOM event.
 */
const emit = defineEmits<{
  "update:modelValue": [value: DateRangeValue];
  valueChange: [value: DateRangeValue];
}>();

const attrs = useAttrs();
const isInvalid = computed(() => !!props.error);
const errorMessage = computed(() => (typeof props.error === "string" ? props.error : undefined));
const iconSize = computed(() => CONTROL_ICON_SIZE[props.size ?? "md"]);

// React uses useId() here; this is Vue's equivalent. The group is a plain
// <div role="group">, so its name and description have to be wired by hand.
const generatedId = useId();
const labelId = `${generatedId}-label`;
const helperId = `${generatedId}-helper`;
const errorId = `${generatedId}-error`;

const coarse = useCoarsePointer();

const open = ref(false);
const rowEl = ref<HTMLDivElement | null>(null);
const activeDayEl = ref<HTMLButtonElement | null>(null);
const startEl = ref<HTMLInputElement | null>(null);
const endEl = ref<HTMLInputElement | null>(null);

// `defaultValue` seeds the uncontrolled range once; a later change to it must
// not overwrite what the user has picked.
const uncontrolled = ref<DateRangeValue>({
  start: props.defaultValue?.start ?? "",
  end: props.defaultValue?.end ?? "",
});
const current = computed<DateRangeValue>(() =>
  props.modelValue
    ? { start: props.modelValue.start ?? "", end: props.modelValue.end ?? "" }
    : uncontrolled.value,
);

function update(next: DateRangeValue) {
  uncontrolled.value = next;
  emit("update:modelValue", next);
  emit("valueChange", next);
}

function onFieldInput(side: Side, event: Event) {
  const next = (event.target as HTMLInputElement).value;
  update(
    side === "start"
      ? { start: next, end: current.value.end }
      : { start: current.value.start, end: next },
  );
}

function captureField(side: Side, el: unknown) {
  const node = (el as HTMLInputElement | null) ?? null;
  if (side === "start") startEl.value = node;
  else endEl.value = node;
}

const describedBy = computed(
  () =>
    [
      props.helperText && !isInvalid.value ? helperId : null,
      isInvalid.value && errorMessage.value ? errorId : null,
    ]
      .filter(Boolean)
      .join(" ") || undefined,
);

const rootClass = computed(() =>
  clsx(inputFieldStyles({ size: props.size }), "date-range", attrs.class as string),
);

/** The per-end attributes; the markup around them is identical for both. */
function fieldProps(side: Side) {
  const isStart = side === "start";
  return definedOnly({
    // Native date inputs are never `:placeholder-shown`; flag empty so the
    // mm/dd/yyyy chrome renders in the placeholder colour.
    "data-empty": (isStart ? current.value.start : current.value.end) ? undefined : true,
    value: isStart ? current.value.start : current.value.end,
    // The filled end becomes the other's bound, so the range can't invert.
    min: isStart ? props.min : current.value.start || props.min,
    max: isStart ? current.value.end || props.max : props.max,
    name: isStart ? props.startName : props.endName,
    required: props.required,
    disabled: props.disabled,
    "aria-label": isStart ? props.startLabel : props.endLabel,
    "aria-invalid": isInvalid.value || undefined,
  });
}

const pickerLabel = (side: Side) =>
  `${side === "start" ? props.startLabel : props.endLabel} — choose date`;

/** Touch path: hand the end over to the OS picker rather than the popover. */
const openNativePicker = (side: Side) =>
  openDatePicker(side === "start" ? startEl.value : endEl.value);

// Ark keeps aria-controls on the trigger at all times, but the popup it names is
// only mounted while open. popupControls drops it while closed — spread, not
// bound, so an undefined never strips the machine's own value. See props.ts.
const controls = computed(() => definedOnly(popupControls(open.value)));
const positioning = datePopoverPositioning(() => rowEl.value);
</script>

<template>
  <div
    role="group"
    :aria-labelledby="label ? labelId : undefined"
    :aria-describedby="describedBy"
    :data-disabled="disabled || undefined"
    :class="rootClass"
    v-bind="{ ...$attrs, class: undefined }"
  >
    <span v-if="label" :id="labelId" class="field__label">
      {{ label }}
      <span v-if="required" class="field__required" aria-hidden="true" />
    </span>

    <!--
      The row is written twice because a Vue template has no way to name a
      fragment and place it in two branches — React assigns it to a variable.
      The two differ only in the start button: an Ark popover trigger on a fine
      pointer, a plain button that calls `showPicker()` on a coarse one.
    -->
    <div v-if="coarse" ref="rowEl" class="date-range__row">
      <template v-for="side in SIDES" :key="side">
        <span
          v-if="side === 'end'"
          class="date-range__separator text-default-body-large"
          aria-hidden="true"
        >
          <slot name="separator">{{ separator }}</slot>
        </span>
        <div class="input-affix date-range__field">
          <button
            type="button"
            class="input-affix__adornment input-affix__adornment--start input-affix__action"
            :disabled="disabled"
            :aria-label="pickerLabel(side)"
            @click="openNativePicker(side)"
          >
            <Icon name="calendar" :size="iconSize" />
          </button>
          <input
            :ref="(el) => captureField(side, el)"
            type="date"
            class="field__control field__control--affix-start"
            v-bind="fieldProps(side)"
            @input="(event) => onFieldInput(side, event)"
          />
        </div>
      </template>
    </div>

    <ArkPopover.Root
      v-else
      :open="open"
      :positioning="positioning"
      :initial-focus-el="() => activeDayEl"
      @open-change="(details) => (open = details.open)"
    >
      <div ref="rowEl" class="date-range__row">
        <template v-for="side in SIDES" :key="side">
          <span
            v-if="side === 'end'"
            class="date-range__separator text-default-body-large"
            aria-hidden="true"
          >
            <slot name="separator">{{ separator }}</slot>
          </span>
          <div class="input-affix date-range__field">
            <ArkPopover.Trigger v-if="side === 'start'" as-child v-bind="controls">
              <button
                type="button"
                class="input-affix__adornment input-affix__adornment--start input-affix__action"
                :disabled="disabled"
                :aria-label="pickerLabel('start')"
              >
                <Icon name="calendar" :size="iconSize" />
              </button>
            </ArkPopover.Trigger>
            <button
              v-else
              type="button"
              class="input-affix__adornment input-affix__adornment--start input-affix__action"
              :disabled="disabled"
              :aria-label="pickerLabel('end')"
              @click="open = true"
            >
              <Icon name="calendar" :size="iconSize" />
            </button>
            <input
              :ref="(el) => captureField(side, el)"
              type="date"
              class="field__control field__control--affix-start"
              v-bind="fieldProps(side)"
              @input="(event) => onFieldInput(side, event)"
            />
          </div>
        </template>
      </div>
      <DatePopover
        :container="portalContainer"
        :label="`${startLabel} — ${endLabel}, choose dates`"
      >
        <Calendar
          mode="range"
          :num-months="2"
          :range-value="{
            start: parseISODate(current.start),
            end: parseISODate(current.end),
          }"
          :min="parseISODate(min)"
          :max="parseISODate(max)"
          :on-range-change="
            (r) =>
              update({
                start: r.start ? toISODate(r.start) : '',
                end: r.end ? toISODate(r.end) : '',
              })
          "
          :on-range-complete="() => (open = false)"
          :on-active-day="(el: HTMLButtonElement | null) => (activeDayEl = el)"
        />
      </DatePopover>
    </ArkPopover.Root>

    <p v-if="helperText && !isInvalid" :id="helperId" class="field__description">
      {{ helperText }}
    </p>
    <FieldError v-if="isInvalid && errorMessage" :id="errorId" :message="errorMessage" />
  </div>
</template>
