// packages/vue/src/components/Checkbox/Checkbox.vue
<script setup lang="ts">
import { computed, useAttrs } from "vue";
import { Checkbox as ArkCheckbox } from "@ark-ui/vue";
import { clsx } from "clsx";
import { definedOnly } from "../../props.js";
import { OMIT_ARIA } from "@ui-organized/core";
import Icon from "../Icon/Icon.vue";
import type { CheckboxProps } from "./Checkbox.types.js";
import "@ui-organized/core/components/Checkbox/Checkbox.css";

defineOptions({ inheritAttrs: false });
const props = withDefaults(defineProps<CheckboxProps>(), { checked: undefined });
/**
 * `checked` is a plain prop plus an `update:checked` emit rather than
 * `defineModel`, and its `undefined` default is load-bearing.
 *
 * Vue casts an *absent* Boolean prop to `false` rather than leaving it
 * undefined, unless the prop declares a default. Without one, `checked` arrives
 * as `false` on a control nobody is controlling, Ark reads that as "controlled
 * and off", and `defaultChecked` is silently overridden — it renders unchecked
 * and nothing reports a problem. `defineModel` gives no way to declare that
 * default (its runtime options do not accept one), so the prop and emit are
 * written out. `v-model:checked` still works: that is exactly what it compiles
 * to.
 *
 * This is the third shape of the same Vue rule — see ../../props.ts.
 */
const emit = defineEmits<{
  "update:checked": [checked: boolean];
  checkedChange: [checked: boolean];
}>();

const attrs = useAttrs();

// Declared as `ariaLabel` — see the prop's doc comment for why the hyphenated
// spelling cannot work. `attrs` is still checked, for a consumer who spreads the
// attribute in from a wrapper that does not declare it.
const ariaLabel = computed(
  () => props.ariaLabel ?? (attrs["aria-label"] as string | undefined),
);

/**
 * The ARIA overrides for the hidden input, as an object that is *empty* when a
 * label exists.
 *
 * This cannot be written the way React and Svelte write it. There, passing
 * `undefined` means "I am not setting this" and zag's mergeProps keeps the
 * machine's value. Vue's attribute merge is last-wins and not undefined-aware,
 * so an explicit `:aria-labelledby="undefined"` *removes* the reference Ark just
 * computed — silently, and only in the case where the label exists and the
 * reference was correct. The only way to leave an attribute alone in Vue is not
 * to pass it, hence spreading a conditional object.
 */
const hiddenInputAria = computed(() =>
  props.label
    ? {}
    : definedOnly({ "aria-labelledby": OMIT_ARIA, "aria-label": ariaLabel.value }),
);
const rootClass = computed(() =>
  clsx("checkbox", props.disabled && "checkbox--disabled", attrs.class as string),
);

// Ark folds indeterminate into the checked value rather than taking it as a
// separate prop, so the facade translates it at the boundary — and back again in
// the callback, where only a true `true` counts as checked.
/**
 * Ark's checked state, spelled out rather than imported from @zag-js/checkbox —
 * that is a transitive dependency of Ark, not one this package declares, and
 * reaching into it to borrow a two-member union would couple us to Ark's
 * internals for no benefit.
 */
type CheckedState = boolean | "indeterminate";

const arkChecked = computed<CheckedState | undefined>(() =>
  props.indeterminate ? "indeterminate" : props.checked,
);

// Spread rather than bound one by one — see ../../props.ts. Ark declares
// `checked` with a default, so an explicit undefined would override
// `defaultChecked` rather than defer to it.
const rootProps = computed(() =>
  definedOnly({
    checked: arkChecked.value,
    defaultChecked: props.defaultChecked,
    disabled: props.disabled,
    required: props.required,
    name: props.name,
    id: props.id,
  }),
);
</script>

<!-- Ark's Checkbox.Root *is* the <label>. -->
<template>
  <ArkCheckbox.Root
    :class="rootClass"
    v-bind="rootProps"
    @checked-change="
      (details) => {
        emit('update:checked', details.checked === true);
        emit('checkedChange', details.checked === true);
      }
    "
  >
    <ArkCheckbox.Control class="checkbox__control">
      <ArkCheckbox.Indicator class="checkbox__indicator">
        <span v-if="indeterminate" class="checkbox__indicator--indeterminate" />
        <Icon v-else name="check" :size="16" class="checkbox__check" />
      </ArkCheckbox.Indicator>
    </ArkCheckbox.Control>
    <ArkCheckbox.Label v-if="label" class="checkbox__label text-default-body-large">
      {{ label }}
    </ArkCheckbox.Label>
    <!--
      Ark points the input at the Label part unconditionally. With no `label`
      there is no such element, so the reference dangles — and a dangling
      aria-labelledby outranks aria-label, leaving the box nameless.
    -->
    <ArkCheckbox.HiddenInput
      v-bind="hiddenInputAria"
    />
  </ArkCheckbox.Root>
</template>

// packages/angular/src/lib/checkbox/checkbox.ts
import {
  Component,
  booleanAttribute,
  computed,
  forwardRef,
  inject,
  input,
  model,
  output,
  signal,
  type Signal,
} from "@angular/core";
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from "@angular/forms";
import { clsx } from "clsx";
import { UioInteractionState } from "../interaction-state.js";
import { UioPart } from "../part.js";
import { VISUALLY_HIDDEN_INPUT, nextMachineId } from "../part-ids.js";
import { UioIcon } from "../icons/icon.js";

/**
 * A box that is ticked, empty, or neither.
 *
 * Built the way Switch is — the root `<label>` *is* the control, the box and
 * its indicator are `aria-hidden` decoration, and a visually-hidden input takes
 * the focus and carries the value into a form. What Switch does not have is the
 * third state.
 *
 * ── Indeterminate ──────────────────────────────────────────────────────────
 *
 * Ark folds it into the checked value (`checked="indeterminate"`); the facade
 * across all four libraries keeps it a separate boolean, because "some of the
 * children are ticked" is a different question from "is this ticked" and a
 * caller answering the first should not have to widen the type of the second.
 * So `indeterminate` wins over `checked` throughout — the state word, the
 * indicator's dash, and the hidden input, which comes out unchecked with its
 * `indeterminate` *property* set. A property and not an attribute because
 * there is no such attribute, which is also why the parity gate cannot see it.
 *
 * The indicator carries `hidden` unless the box is ticked, as Ark's does, and
 * is painted anyway: `.checkbox__indicator` sets `display`, which outranks the
 * attribute. That is the stylesheet's decision and it is shared by all four
 * libraries — reproducing the attribute is what keeps them comparable.
 *
 * ```html
 * <label uioCheckbox label="Accept" formControlName="accept"></label>
 * <label uioCheckbox label="All" [indeterminate]="some()" [(checked)]="all"></label>
 * ```
 */
@Component({
  selector: "label[uioCheckbox]",
  standalone: true,
  imports: [UioIcon],
  // Reports hover and focus so the shared stylesheet can draw a focus ring —
  // see UioInteractionState for why it is a host directive rather than a base.
  hostDirectives: [UioInteractionState],
  providers: [
    { provide: NG_VALUE_ACCESSOR, useExisting: forwardRef(() => UioCheckbox), multi: true },
  ],
  template: `
    <div
      class="checkbox__control"
      data-scope="checkbox"
      data-part="control"
      aria-hidden="true"
      [id]="partId('control')"
      [attr.data-state]="state()"
      [attr.data-disabled]="flag(disabled())"
      [attr.data-required]="flag(required())"
      [attr.data-hover]="flag(hover())"
      [attr.data-focus]="flag(focus())"
      [attr.data-focus-visible]="flag(focusVisible())"
    >
      <div
        class="checkbox__indicator"
        data-scope="checkbox"
        data-part="indicator"
        [attr.data-state]="state()"
        [attr.data-disabled]="flag(disabled())"
        [attr.data-required]="flag(required())"
        [attr.data-hover]="flag(hover())"
        [attr.data-focus]="flag(focus())"
        [attr.data-focus-visible]="flag(focusVisible())"
        [attr.hidden]="state() === 'checked' ? null : ''"
      >
        @if (indeterminate()) {
          <span class="checkbox__indicator--indeterminate"></span>
        } @else {
          <span uioIcon class="checkbox__check" name="check" [size]="ICON_SIZE"></span>
        }
      </div>
    </div>
    @if (label(); as text) {
      <span
        class="checkbox__label text-default-body-large"
        data-scope="checkbox"
        data-part="label"
        [id]="partId('label')"
        [attr.data-state]="state()"
        [attr.data-disabled]="flag(disabled())"
        [attr.data-required]="flag(required())"
        [attr.data-hover]="flag(hover())"
        [attr.data-focus]="flag(focus())"
        [attr.data-focus-visible]="flag(focusVisible())"
        >{{ text }}</span
      >
    }
    <!--
      Ark points the input at the Label part unconditionally. With no label
      there is no such element, so the reference would dangle — and a dangling
      aria-labelledby outranks aria-label, leaving the box nameless. That is
      what OMIT_ARIA guards in the other three; here the reference is simply not
      written.
    -->
    <input
      type="checkbox"
      value="on"
      [id]="partId('input')"
      [attr.style]="HIDDEN"
      [checked]="checked() && !indeterminate()"
      [indeterminate]="indeterminate()"
      [disabled]="disabled()"
      [attr.required]="required() ? '' : null"
      [attr.name]="name()"
      [attr.aria-invalid]="invalid() ? 'true' : 'false'"
      [attr.aria-labelledby]="label() ? partId('label') : null"
      [attr.aria-label]="label() ? null : ariaLabel()"
      (change)="toggle($event)"
      (blur)="onTouched()"
    />
  `,
  host: {
    "[class]": "hostClass()",
    "[id]": "rootId",
    "[attr.for]": "partId('input')",
    /** Not on `UioPart`: no stylesheet selects on it. See UioSwitch. */
    "[attr.data-required]": "flag(required())",
  },
})
export class UioCheckbox extends UioPart implements ControlValueAccessor {
  readonly scope = "checkbox";
  readonly part = "root";

  private readonly interaction = inject(UioInteractionState);
  override readonly hover: Signal<boolean> = this.interaction.hover;
  override readonly focus: Signal<boolean> = this.interaction.focus;
  override readonly focusVisible: Signal<boolean> = this.interaction.focusVisible;

  readonly checked = model(false);
  readonly indeterminate = input(false, { transform: booleanAttribute });
  readonly label = input<string | undefined>(undefined);
  readonly required = input(false, { transform: booleanAttribute });
  readonly name = input<string | undefined>(undefined);
  /** Only used when there is no visible label — with one, the label names the box. */
  readonly ariaLabel = input<string | undefined>(undefined, { alias: "aria-label" });
  readonly checkedChange = output<boolean>();

  /** `disabled` comes from the caller *or* from a reactive form's disabled state. */
  protected readonly disabledInput = input(false, {
    alias: "disabled",
    transform: booleanAttribute,
  });
  private readonly formDisabled = signal(false);
  override readonly disabled: Signal<boolean> = computed(
    () => this.disabledInput() || this.formDisabled(),
  );
  override readonly state = computed(() => {
    if (this.indeterminate()) return "indeterminate";
    return this.checked() ? "checked" : "unchecked";
  });

  private readonly machine = nextMachineId();
  protected get rootId(): string {
    return `${this.scope}:${this.machine}`;
  }
  protected partId(part: string): string {
    return `${this.scope}:${this.machine}:${part}`;
  }

  protected readonly ICON_SIZE = 16;
  protected readonly HIDDEN = VISUALLY_HIDDEN_INPUT;
  protected readonly hostClass = computed(() =>
    clsx("checkbox", this.disabled() && "checkbox--disabled"),
  );

  protected onTouched: () => void = () => {};
  private onChange: (value: boolean) => void = () => {};

  protected toggle(event: Event): void {
    const next = (event.target as HTMLInputElement).checked;
    this.checked.set(next);
    this.checkedChange.emit(next);
    this.onChange(next);
  }

  writeValue(value: boolean): void {
    this.checked.set(!!value);
  }
  registerOnChange(fn: (value: boolean) => void): void {
    this.onChange = fn;
  }
  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }
  setDisabledState(isDisabled: boolean): void {
    this.formDisabled.set(isDisabled);
  }
}
