// tooling/parity/src/cases/TagsInput.tsx
import type { ComponentType } from "react";
import { TagsInput as RTagsInput } from "@ui-organized/react";
import TagsInputFixture from "../fixtures/TagsInputFixture.svelte";
import { SIZES, type ParitySpec } from "./spec.js";

const tags = ["design", "system"];

const spec: ParitySpec = {
  component: "TagsInput",
  react: (p) => <RTagsInput {...p} />,
  svelte: TagsInputFixture as unknown as ComponentType<any>,
  cases: [
    { name: "default" },
    { name: "with label", props: { label: "Tags" } },
    { name: "required", props: { label: "Tags", required: true } },
    { name: "helper text", props: { label: "Tags", helperText: "Comma separated" } },
    { name: "error message", props: { label: "Tags", error: "Too many" } },
    { name: "invalid without message", props: { label: "Tags", error: true } },
    { name: "helper hidden by error", props: { label: "T", helperText: "H", error: "Bad" } },
    ...SIZES.map((size) => ({ name: `size/${size}`, props: { size, label: "Tags" } })),
    { name: "placeholder", props: { placeholder: "Add a tag" } },
    // The chips are read back from the machine, not mapped over the prop, so
    // a tag list that never reached the machine renders as an empty well.
    { name: "default value", props: { defaultValue: tags } },
    { name: "controlled value", props: { value: tags } },
    { name: "single tag", props: { defaultValue: ["one"] } },
    // At `max` the machine stops accepting entries; the attribute that says so
    // sits on the control.
    { name: "at max", props: { defaultValue: tags, max: 2 } },
    { name: "under max", props: { defaultValue: tags, max: 5 } },
    { name: "not editable", props: { defaultValue: tags, editable: false } },
    { name: "delimiter", props: { delimiter: ";" } },
    { name: "add on paste", props: { addOnPaste: true } },
    { name: "disabled", props: { label: "Tags", defaultValue: tags, disabled: true } },
    { name: "read only", props: { label: "Tags", defaultValue: tags, readOnly: true } },
    { name: "named", props: { name: "tags", defaultValue: tags } },
  ],
};

export default spec;

// packages/svelte/src/lib/components/TagsInput/TagsInput.svelte
<script lang="ts">
  import { TagsInput as ArkTagsInput } from "@ark-ui/svelte";
  import { clsx } from "clsx";
  import { tagsInputStyles } from "@ui-organized/core";
  import Icon from "../Icon/Icon.svelte";
  import FieldError from "../FieldError/FieldError.svelte";
  import type { TagsInputProps } from "./TagsInput.types.js";
  import "@ui-organized/core/components/TagsInput/TagsInput.css";

  /** Delete affordance inside a tag — always the small edge, at every control
   *  size, because it sits inside the chip rather than beside it. */
  const DELETE_ICON_SIZE = 12;

  let {
    label,
    helperText,
    error,
    value = $bindable(),
    defaultValue,
    onValueChange,
    placeholder,
    size,
    max,
    editable,
    delimiter,
    addOnPaste,
    required,
    disabled,
    readOnly,
    name,
    class: className,
  }: TagsInputProps = $props();

  const isInvalid = $derived(!!error);
  const errorMessage = $derived(typeof error === "string" ? error : undefined);
</script>

<ArkTagsInput.Root
  class={clsx(tagsInputStyles({ size }), className)}
  {value}
  {defaultValue}
  onValueChange={(details) => {
    value = details.value;
    onValueChange?.(details.value);
  }}
  {max}
  {editable}
  {delimiter}
  {addOnPaste}
  invalid={isInvalid}
  {required}
  {disabled}
  {readOnly}
  {name}
>
  {#if label}
    <ArkTagsInput.Label class="field__label">
      {label}
      {#if required}<span class="field__required" aria-hidden="true"></span>{/if}
    </ArkTagsInput.Label>
  {/if}
  <ArkTagsInput.Control class="tags-input__control">
    <!--
      The tags are machine state, not children, so the list is read back from the
      context rather than mapped over the `value` prop — that keeps in-place
      editing (ItemInput) working on the machine's copy. The Svelte context part
      hands the api over as an accessor, hence `api()`.
    -->
    <ArkTagsInput.Context>
      {#snippet render(api)}
        {#each api().value as tag, index (`${tag}-${index}`)}
          <ArkTagsInput.Item {index} value={tag}>
            <ArkTagsInput.ItemPreview class="tags-input__tag">
              <ArkTagsInput.ItemText class="tags-input__tag-label">{tag}</ArkTagsInput.ItemText>
              <ArkTagsInput.ItemDeleteTrigger class="tags-input__tag-delete">
                <Icon name="close" size={DELETE_ICON_SIZE} />
              </ArkTagsInput.ItemDeleteTrigger>
            </ArkTagsInput.ItemPreview>
            <ArkTagsInput.ItemInput class="tags-input__tag-input" />
          </ArkTagsInput.Item>
        {/each}
      {/snippet}
    </ArkTagsInput.Context>
    <ArkTagsInput.Input class="tags-input__entry" {placeholder} />
  </ArkTagsInput.Control>
  {#if helperText && !isInvalid}
    <span class="field__description">{helperText}</span>
  {/if}
  {#if isInvalid && errorMessage}
    <FieldError message={errorMessage} />
  {/if}
  <ArkTagsInput.HiddenInput />
</ArkTagsInput.Root>
