// packages/react/src/components/Splitter/Splitter.tsx
import { useMemo, Fragment } from "react";
import { Splitter as ArkSplitter } from "@ark-ui/react";
import { clsx } from "clsx";
import { splitterStyles } from "@ui-organized/core";
import type { SplitterProps } from "./Splitter.types.js";
import "@ui-organized/core/components/Splitter/Splitter.css";

export function Splitter({
  panels,
  size,
  defaultSize,
  onResize,
  onResizeEnd,
  orientation = "horizontal",
  variant,
  className,
}: SplitterProps) {
  /* The machine takes its own panel descriptors, not our render data — strip
     `content` so a changed React node never looks like a changed constraint. */
  const panelData = useMemo(
    () =>
      panels.map(({ id, minSize, maxSize, collapsible, collapsedSize }) => ({
        id,
        minSize,
        maxSize,
        collapsible,
        collapsedSize,
      })),
    [panels],
  );

  return (
    <ArkSplitter.Root
      className={clsx(splitterStyles({ orientation, variant }), className)}
      panels={panelData}
      size={size}
      defaultSize={defaultSize}
      onResize={onResize && ((details) => onResize(details.size))}
      onResizeEnd={onResizeEnd && ((details) => onResizeEnd(details.size))}
      orientation={orientation}
    >
      {panels.map((panel, index) => (
        <Fragment key={panel.id}>
          <ArkSplitter.Panel id={panel.id} className="splitter__panel">
            {panel.content}
          </ArkSplitter.Panel>
          {/* A handle sits between adjacent panels, so the last panel has none.
              zag identifies it by the literal "before:after" pair of ids. */}
          {index < panels.length - 1 && (
            <ArkSplitter.ResizeTrigger
              id={`${panel.id}:${panels[index + 1]!.id}`}
              className="splitter__trigger"
              // The handle is a <button role="separator"> whose only child is a
              // decorative grip, so it had no accessible name — a keyboard user
              // landed on an unnamed control with arrow keys that did something
              // unexplained. Naming it after the two panels it sits between says
              // what moving it will do.
              aria-label={`Resize ${panel.label ?? panel.id} and ${
                panels[index + 1]!.label ?? panels[index + 1]!.id
              }`}
            >
              <span className="splitter__grip" aria-hidden="true" />
            </ArkSplitter.ResizeTrigger>
          )}
        </Fragment>
      ))}
    </ArkSplitter.Root>
  );
}

// packages/vue/src/components/Splitter/Splitter.vue
<script setup lang="ts">
import { computed, useAttrs } from "vue";
import { Splitter as ArkSplitter } from "@ark-ui/vue";
import { clsx } from "clsx";
import { splitterStyles } from "@ui-organized/core";
import { definedOnly } from "../../props.js";
import type { SplitterProps } from "./Splitter.types.js";
import "@ui-organized/core/components/Splitter/Splitter.css";

defineOptions({ inheritAttrs: false });
const props = withDefaults(defineProps<SplitterProps>(), {
  orientation: "horizontal",
});
const emit = defineEmits<{
  "update:size": [size: number[]];
  resize: [size: number[]];
  resizeEnd: [size: number[]];
}>();

const attrs = useAttrs();
const rootClass = computed(() =>
  clsx(
    splitterStyles({ orientation: props.orientation, variant: props.variant }),
    attrs.class as string,
  ),
);

/* The machine takes its own panel descriptors, not our render data — strip
   `content` so a changed component never looks like a changed constraint. */
const panelData = computed(() =>
  props.panels.map(({ id, minSize, maxSize, collapsible, collapsedSize }) => ({
    id,
    minSize,
    maxSize,
    collapsible,
    collapsedSize,
  })),
);

const rootProps = computed(() => definedOnly({ size: props.size, defaultSize: props.defaultSize }));

// Written here rather than inline: a Vue template expression cannot carry an
// object type annotation, and the handlers' details argument needs one.
function onResize(details: { size: number[] }) {
  emit("update:size", details.size);
  emit("resize", details.size);
}
function onResizeEnd(details: { size: number[] }) {
  emit("resizeEnd", details.size);
}
const isString = (v: unknown) => typeof v === "string";
</script>

<template>
  <ArkSplitter.Root
    :class="rootClass"
    :panels="panelData"
    v-bind="rootProps"
    :orientation="orientation"
    @resize="onResize"
    @resize-end="onResizeEnd"
  >
    <template v-for="(panel, index) in panels" :key="panel.id">
      <ArkSplitter.Panel :id="panel.id" class="splitter__panel">
        <template v-if="isString(panel.content)">{{ panel.content }}</template>
        <component :is="panel.content" v-else-if="panel.content" />
      </ArkSplitter.Panel>
      <!--
        A handle sits between adjacent panels, so the last panel has none.
        zag identifies it by the literal "before:after" pair of ids.
      -->
      <!-- The handle is a <button role="separator"> whose only child is a
           decorative grip, so it had no accessible name — a keyboard user landed
           on an unnamed control with arrow keys that did something unexplained.
           Naming it after the two panels it sits between says what moving it
           will do. Same name as the React library's. -->
      <ArkSplitter.ResizeTrigger
        v-if="index < panels.length - 1"
        :id="`${panel.id}:${panels[index + 1]!.id}`"
        class="splitter__trigger"
        :aria-label="`Resize ${panel.label ?? panel.id} and ${
          panels[index + 1]!.label ?? panels[index + 1]!.id
        }`"
      >
        <span class="splitter__grip" aria-hidden="true" />
      </ArkSplitter.ResizeTrigger>
    </template>
  </ArkSplitter.Root>
</template>
