// packages/vue/src/components/Input/Input.vue
<script setup lang="ts">
import { computed, useAttrs } from "vue";
import { Field } from "@ark-ui/vue";
import { clsx } from "clsx";
import { inputFieldStyles } from "@ui-organized/core";
import { definedOnly } from "../../props.js";
import FieldError from "../FieldError/FieldError.vue";
import type { InputProps } from "./Input.types.js";
import "@ui-organized/core/components/Input/Input.css";

defineOptions({ inheritAttrs: false });
const props = defineProps<InputProps>();
const emit = defineEmits<{ "update:modelValue": [value: string] }>();

const attrs = useAttrs();
const isInvalid = computed(() => !!props.error);
const errorMessage = computed(() =>
  typeof props.error === "string" ? props.error : undefined,
);
const rootClass = computed(() =>
  clsx(inputFieldStyles({ size: props.size }), attrs.class as string),
);
const inputProps = computed(() =>
  definedOnly({
    ...attrs,
    class: undefined,
    required: props.required,
    disabled: props.disabled,
    value: props.modelValue,
  }),
);
</script>

<template>
  <Field.Root :class="rootClass" :invalid="isInvalid">
    <Field.Label v-if="label" class="field__label">
      {{ label }}
      <span v-if="required" class="field__required" aria-hidden="true" />
    </Field.Label>
    <Field.Input
      class="field__control"
      v-bind="inputProps"
      @input="emit('update:modelValue', ($event.target as HTMLInputElement).value)"
    />
    <Field.HelperText v-if="helperText && !isInvalid" class="field__description">
      {{ helperText }}
    </Field.HelperText>
    <!--
      Ark's ErrorText renders only while the Field is invalid, and `asChild`
      hands its props to whatever replaces it — here the shared FieldError, so
      the message keeps its icon and its aria-describedby wiring.
    -->
    <Field.ErrorText v-if="isInvalid && errorMessage" as-child>
      <FieldError :message="errorMessage" />
    </Field.ErrorText>
  </Field.Root>
</template>

// packages/svelte/src/lib/components/Input/Input.svelte
<script lang="ts">
  import { Field } from "@ark-ui/svelte";
  import { clsx } from "clsx";
  import { inputFieldStyles } from "@ui-organized/core";
  import FieldError from "../FieldError/FieldError.svelte";
  import type { InputProps } from "./Input.types.js";
  import "@ui-organized/core/components/Input/Input.css";

  let {
    label,
    helperText,
    error,
    size,
    required,
    id,
    class: className,
    value = $bindable(),
    ...inputProps
  }: InputProps = $props();

  const isInvalid = $derived(!!error);
  const errorMessage = $derived(typeof error === "string" ? error : undefined);
</script>

<Field.Root class={clsx(inputFieldStyles({ size }), className)} invalid={isInvalid} {id}>
  {#if label}
    <Field.Label class="field__label">
      {label}
      {#if required}<span class="field__required" aria-hidden="true"></span>{/if}
    </Field.Label>
  {/if}
  <Field.Input class="field__control" {required} bind:value {...inputProps} />
  {#if helperText && !isInvalid}
    <Field.HelperText class="field__description">{helperText}</Field.HelperText>
  {/if}
  {#if isInvalid && errorMessage}
    <!--
      Ark's ErrorText renders only while the Field is invalid, and `asChild`
      hands its props to whatever we render in its place — here the shared
      FieldError, so the message keeps its icon and its aria-describedby wiring.
    -->
    <Field.ErrorText>
      {#snippet asChild(props)}
        <FieldError {...props()} message={errorMessage} />
      {/snippet}
    </Field.ErrorText>
  {/if}
</Field.Root>
