// packages/svelte/src/lib/components/Alert/Alert.svelte
<!--
  A prominent message about the state of something.

  `role="alert"` is the component's own, not the caller's job: an alert that
  assistive technology does not announce is a coloured box.

  There is no Ark machine behind this one — Ark UI has no Alert primitive — so
  the markup here *is* the contract, and the parity gate compares it element for
  element against the React library's.
-->
<script lang="ts">
  import { clsx } from "clsx";
  import { alertStyles } from "@ui-organized/core";
  import type { CanonicalIconName } from "@ui-organized/utils";
  import Icon from "../Icon/Icon.svelte";
  import type { AlertProps } from "./Alert.types.js";
  import "@ui-organized/core/components/Alert/Alert.css";

  /** Each variant announces itself with its own glyph before anyone reads the text. */
  const VARIANT_ICONS: Record<NonNullable<AlertProps["variant"]>, CanonicalIconName> = {
    info:    "info",
    success: "check-circle",
    warning: "alert-triangle",
    error:   "alert-circle",
  };

  const ICON_SIZE = 20;

  let { variant = "info", title, children, onDismiss, class: className }: AlertProps = $props();
</script>

<div role="alert" class={clsx(alertStyles({ variant }), className)}>
  <span class="alert__icon">
    <Icon name={VARIANT_ICONS[variant]} size={ICON_SIZE} />
  </span>
  <div class="alert__body">
    {#if title}
      <div class="alert__title text-strong-body-medium">{title}</div>
    {/if}
    <div class="alert__message text-default-body-medium">{@render children()}</div>
  </div>
  {#if onDismiss}
    <button type="button" class="alert__dismiss" aria-label="Dismiss alert" onclick={() => onDismiss()}>
      <Icon name="close" size={ICON_SIZE} />
    </button>
  {/if}
</div>

// packages/react/src/components/Alert/Alert.tsx
import { clsx } from "clsx";
import { alertStyles } from "@ui-organized/core";
import { Icon } from "../Icon/index.js";
import type { AlertProps } from "./Alert.types.js";
import type { CanonicalIconName } from "@ui-organized/utils";
import "@ui-organized/core/components/Alert/Alert.css";

const VARIANT_ICONS: Record<NonNullable<AlertProps["variant"]>, CanonicalIconName> = {
  info:    "info",
  success: "check-circle",
  warning: "alert-triangle",
  error:   "alert-circle",
};

export function Alert({ variant = "info", title, children, onDismiss, className }: AlertProps) {
  return (
    <div role="alert" className={clsx(alertStyles({ variant }), className)}>
      <span className="alert__icon">
        <Icon name={VARIANT_ICONS[variant]} size={20} />
      </span>
      <div className="alert__body">
        {title && <div className="alert__title text-strong-body-medium">{title}</div>}
        <div className="alert__message text-default-body-medium">{children}</div>
      </div>
      {onDismiss && (
        <button
          type="button"
          className="alert__dismiss"
          onClick={onDismiss}
          aria-label="Dismiss alert"
        >
          <Icon name="close" size={20} />
        </button>
      )}
    </div>
  );
}
