// packages/svelte/src/lib/components/DatePicker/DatePicker.svelte
<!--
  Calendar-driven date field, backed by Ark's DatePicker machine.

  The public API is ISO date strings; the machine works in `DateValue` objects,
  and the conversion happens at this boundary so nothing downstream has to know
  about `@internationalized/date`.
-->
<script lang="ts">
  import { DatePicker as ArkDatePicker, Portal, parseDate } from "@ark-ui/svelte";
  import { clsx } from "clsx";
  import { CONTROL_ICON_SIZE, datePickerStyles } from "@ui-organized/core";
  import Icon from "../Icon/Icon.svelte";
  import FieldError from "../FieldError/FieldError.svelte";
  import type { DatePickerProps } from "./DatePicker.types.js";
  import "@ui-organized/core/components/DatePicker/DatePicker.css";

  /** Weekday header and navigation glyphs stay one step below the cell text. */
  const NAV_ICON_SIZE = 16;

  let {
    label,
    helperText,
    error,
    value = $bindable(),
    defaultValue,
    onValueChange,
    selectionMode,
    min,
    max,
    numOfMonths,
    locale,
    open = $bindable(),
    defaultOpen,
    onOpenChange,
    size = "md",
    variant,
    required,
    disabled,
    readOnly,
    name,
    portalContainer,
    class: className,
  }: DatePickerProps = $props();

  const isInvalid = $derived(!!error);
  const errorMessage = $derived(typeof error === "string" ? error : undefined);
  const iconSize = $derived(CONTROL_ICON_SIZE[size]);

  /** ISO dates in, parsed calendar dates out. */
  const parsedValue = $derived(value ? value.map((d) => parseDate(d)) : undefined);
  const parsedDefault = $derived(defaultValue ? defaultValue.map((d) => parseDate(d)) : undefined);
  const parsedMin = $derived(min ? parseDate(min) : undefined);
  const parsedMax = $derived(max ? parseDate(max) : undefined);
</script>

<ArkDatePicker.Root
  class={clsx(datePickerStyles({ size, variant }), className)}
  value={parsedValue}
  defaultValue={parsedDefault}
  onValueChange={(details) => {
    value = details.value.map(String);
    onValueChange?.(value);
  }}
  {selectionMode}
  min={parsedMin}
  max={parsedMax}
  {numOfMonths}
  {locale}
  bind:open
  {defaultOpen}
  onOpenChange={(details) => onOpenChange?.(details.open)}
  invalid={isInvalid}
  {required}
  {disabled}
  {readOnly}
  {name}
  positioning={{ placement: "bottom-start", gutter: 4 }}
>
  {#if label}
    <ArkDatePicker.Label class="field__label">
      {label}
      {#if required}<span class="field__required" aria-hidden="true"></span>{/if}
    </ArkDatePicker.Label>
  {/if}

  <ArkDatePicker.Control class="date-picker__control">
    <ArkDatePicker.Input class="date-picker__input" index={0} />
    {#if selectionMode === "range"}
      <ArkDatePicker.Input class="date-picker__input" index={1} />
    {/if}
    <ArkDatePicker.Trigger class="date-picker__trigger">
      <Icon name="calendar" size={iconSize} />
    </ArkDatePicker.Trigger>
  </ArkDatePicker.Control>

  <Portal container={portalContainer ?? undefined}>
    <!--
      The positioner class must stay a plain string literal — the
      overlay-stacking test scans for it, and a clsx() call here silently
      unregisters the layer.
    -->
    <ArkDatePicker.Positioner class="date-picker__positioner">
      <ArkDatePicker.Content class="date-picker__popup">
        <ArkDatePicker.View view="day">
          <ArkDatePicker.Context>
            {#snippet render(api)}
              <ArkDatePicker.ViewControl class="date-picker__view-control">
                <ArkDatePicker.PrevTrigger class="date-picker__nav">
                  <Icon name="chevron-left" size={NAV_ICON_SIZE} />
                </ArkDatePicker.PrevTrigger>
                <ArkDatePicker.ViewTrigger class="date-picker__view-trigger">
                  <ArkDatePicker.RangeText />
                </ArkDatePicker.ViewTrigger>
                <ArkDatePicker.NextTrigger class="date-picker__nav">
                  <Icon name="chevron-right" size={NAV_ICON_SIZE} />
                </ArkDatePicker.NextTrigger>
              </ArkDatePicker.ViewControl>

              <ArkDatePicker.Table class="date-picker__table">
                <ArkDatePicker.TableHead>
                  <ArkDatePicker.TableRow>
                    {#each api().weekDays as day (day.long)}
                      <ArkDatePicker.TableHeader
                        class="date-picker__weekday"
                        aria-label={day.long}
                      >
                        {day.narrow}
                      </ArkDatePicker.TableHeader>
                    {/each}
                  </ArkDatePicker.TableRow>
                </ArkDatePicker.TableHead>
                <ArkDatePicker.TableBody>
                  {#each api().weeks as week, weekIndex (weekIndex)}
                    <ArkDatePicker.TableRow>
                      {#each week as day, dayIndex (dayIndex)}
                        <ArkDatePicker.TableCell value={day} class="date-picker__cell">
                          <ArkDatePicker.TableCellTrigger class="date-picker__day">
                            {day.day}
                          </ArkDatePicker.TableCellTrigger>
                        </ArkDatePicker.TableCell>
                      {/each}
                    </ArkDatePicker.TableRow>
                  {/each}
                </ArkDatePicker.TableBody>
              </ArkDatePicker.Table>
            {/snippet}
          </ArkDatePicker.Context>
        </ArkDatePicker.View>
      </ArkDatePicker.Content>
    </ArkDatePicker.Positioner>
  </Portal>

  {#if helperText && !isInvalid}
    <span class="field__description">{helperText}</span>
  {/if}
  {#if isInvalid && errorMessage}
    <FieldError message={errorMessage} />
  {/if}
</ArkDatePicker.Root>

// packages/vue/src/components/DatePicker/DatePicker.vue
<!--
  Calendar-driven date field, backed by Ark's DatePicker machine.

  The public API is ISO date strings; the machine works in `DateValue` objects,
  and the conversion happens at this boundary so nothing downstream has to know
  about `@internationalized/date`.
-->
<script setup lang="ts">
import { computed, useAttrs } from "vue";
import { DatePicker as ArkDatePicker, parseDate } from "@ark-ui/vue";
import { clsx } from "clsx";
import { CONTROL_ICON_SIZE, datePickerStyles } from "@ui-organized/core";
import { definedOnly } from "../../props.js";
import Icon from "../Icon/Icon.vue";
import FieldError from "../FieldError/FieldError.vue";
import type { DatePickerProps } from "./DatePicker.types.js";
import "@ui-organized/core/components/DatePicker/DatePicker.css";

/** Weekday header and navigation glyphs stay one step below the cell text. */
const NAV_ICON_SIZE = 16;

defineOptions({ inheritAttrs: false });
// Every boolean forwarded to Ark below must default to `undefined`. Vue casts an
// absent Boolean prop to `false`, and `definedOnly` then forwards that as a
// deliberate choice — see ../../props.ts. `open: false` in particular means
// "controlled and closed" and would pin the calendar shut forever.
const props = withDefaults(defineProps<DatePickerProps>(), {
  size: "md",
  open: undefined,
  defaultOpen: undefined,
  required: undefined,
  disabled: undefined,
  readOnly: undefined,
});
const emit = defineEmits<{
  "update:modelValue": [value: string[]];
  valueChange: [value: string[]];
  "update:open": [open: boolean];
  openChange: [open: boolean];
}>();

const attrs = useAttrs();
const isInvalid = computed(() => !!props.error);
const errorMessage = computed(() => (typeof props.error === "string" ? props.error : undefined));
const iconSize = computed(() => CONTROL_ICON_SIZE[props.size]);

const rootClass = computed(() =>
  clsx(datePickerStyles({ size: props.size, variant: props.variant }), attrs.class as string),
);

// ISO dates in, parsed calendar dates out. Ark Vue names the controlled value
// `modelValue`; see Select for the same rename.
const rootProps = computed(() =>
  definedOnly({
    modelValue: props.modelValue ? props.modelValue.map((d) => parseDate(d)) : undefined,
    defaultValue: props.defaultValue ? props.defaultValue.map((d) => parseDate(d)) : undefined,
    selectionMode: props.selectionMode,
    min: props.min ? parseDate(props.min) : undefined,
    max: props.max ? parseDate(props.max) : undefined,
    numOfMonths: props.numOfMonths,
    locale: props.locale,
    open: props.open,
    defaultOpen: props.defaultOpen,
    required: props.required,
    disabled: props.disabled,
    readOnly: props.readOnly,
    name: props.name,
  }),
);
</script>

<template>
  <ArkDatePicker.Root
    :class="rootClass"
    v-bind="rootProps"
    :invalid="isInvalid"
    :positioning="{ placement: 'bottom-start', gutter: 4 }"
    @value-change="
      (details) => {
        const next = details.value.map(String);
        emit('update:modelValue', next);
        emit('valueChange', next);
      }
    "
    @open-change="
      (details) => {
        emit('update:open', details.open);
        emit('openChange', details.open);
      }
    "
  >
    <ArkDatePicker.Label v-if="label" class="field__label">
      {{ label }}
      <span v-if="required" class="field__required" aria-hidden="true" />
    </ArkDatePicker.Label>

    <ArkDatePicker.Control class="date-picker__control">
      <ArkDatePicker.Input class="date-picker__input" :index="0" />
      <ArkDatePicker.Input
        v-if="selectionMode === 'range'"
        class="date-picker__input"
        :index="1"
      />
      <ArkDatePicker.Trigger class="date-picker__trigger">
        <Icon name="calendar" :size="iconSize" />
      </ArkDatePicker.Trigger>
    </ArkDatePicker.Control>

    <!--
      Vue has no Ark Portal component — Teleport is built into the framework, and
      Ark Vue relies on it rather than shipping its own.
    -->
    <Teleport :to="portalContainer ?? 'body'">
      <!--
        The positioner class must stay a plain string literal — the
        overlay-stacking test scans for it, and a clsx() call here silently
        unregisters the layer.
      -->
      <ArkDatePicker.Positioner class="date-picker__positioner">
        <ArkDatePicker.Content class="date-picker__popup">
          <ArkDatePicker.View view="day">
            <ArkDatePicker.Context v-slot="api">
              <ArkDatePicker.ViewControl class="date-picker__view-control">
                <ArkDatePicker.PrevTrigger class="date-picker__nav">
                  <Icon name="chevron-left" :size="NAV_ICON_SIZE" />
                </ArkDatePicker.PrevTrigger>
                <ArkDatePicker.ViewTrigger class="date-picker__view-trigger">
                  <ArkDatePicker.RangeText />
                </ArkDatePicker.ViewTrigger>
                <ArkDatePicker.NextTrigger class="date-picker__nav">
                  <Icon name="chevron-right" :size="NAV_ICON_SIZE" />
                </ArkDatePicker.NextTrigger>
              </ArkDatePicker.ViewControl>

              <ArkDatePicker.Table class="date-picker__table">
                <ArkDatePicker.TableHead>
                  <ArkDatePicker.TableRow>
                    <ArkDatePicker.TableHeader
                      v-for="day in api.weekDays"
                      :key="day.long"
                      class="date-picker__weekday"
                      :aria-label="day.long"
                    >
                      {{ day.narrow }}
                    </ArkDatePicker.TableHeader>
                  </ArkDatePicker.TableRow>
                </ArkDatePicker.TableHead>
                <ArkDatePicker.TableBody>
                  <ArkDatePicker.TableRow
                    v-for="(week, weekIndex) in api.weeks"
                    :key="weekIndex"
                  >
                    <ArkDatePicker.TableCell
                      v-for="(day, dayIndex) in week"
                      :key="dayIndex"
                      :value="day"
                      class="date-picker__cell"
                    >
                      <ArkDatePicker.TableCellTrigger class="date-picker__day">
                        {{ day.day }}
                      </ArkDatePicker.TableCellTrigger>
                    </ArkDatePicker.TableCell>
                  </ArkDatePicker.TableRow>
                </ArkDatePicker.TableBody>
              </ArkDatePicker.Table>
            </ArkDatePicker.Context>
          </ArkDatePicker.View>
        </ArkDatePicker.Content>
      </ArkDatePicker.Positioner>
    </Teleport>

    <span v-if="helperText && !isInvalid" class="field__description">{{ helperText }}</span>
    <FieldError v-if="isInvalid && errorMessage" :message="errorMessage" />
  </ArkDatePicker.Root>
</template>
