// packages/svelte-table/src/lib/components/Table/ResizeHandle.svelte
<!--
  Pointer drag and keyboard, on one control.

  The drag is TanStack's own handler; the keyboard is core's `resizeKeyDown`, so
  the two cannot drift. It is a `role="separator"` with `aria-valuenow`, which is
  what makes the column width something a screen reader can report rather than
  something only a mouse can discover.
-->
<script lang="ts" generics="T extends RowData">
  import {
    getResizeHandleProps,
    resizeKeyDown,
    type RowData,
    type TableHeaderInstance,
  } from "@ui-organized/table-core";
  import { getTable } from "../../core/tableContext.js";
  import { svelteProps } from "../../core/props.js";

  let { header }: { header: TableHeaderInstance<T> } = $props();
  const table = getTable<T>();

  const column = $derived(header.column);
  const bounds = $derived.by(() => {
    const width = column.getSize();
    return {
      width,
      min: column.columnDef.minSize ?? 0,
      max: column.columnDef.maxSize ?? width,
    };
  });

  const handleProps = $derived.by(() => {
    const headerDef = column.columnDef.header;
    return getResizeHandleProps({
      columnId: column.id,
      columnLabel: typeof headerDef === "string" ? headerDef : column.id,
      width: bounds.width,
      min: bounds.min,
      max: bounds.max,
      active: column.getIsResizing(),
    });
  });

  /** Stops the header's sort button from firing on the same press. */
  function startResize(event: MouseEvent | TouchEvent) {
    event.stopPropagation();
    header.getResizeHandler()(event);
  }

  function onKeyDown(event: KeyboardEvent) {
    const action = resizeKeyDown(bounds, {
      key: event.key,
      shift: event.shiftKey,
      ctrl: event.ctrlKey,
      meta: event.metaKey,
    });
    if (action.type === "none") return;
    event.preventDefault();
    event.stopPropagation();
    if (action.type === "reset") {
      table.table.setColumnSizing((old: Record<string, number>) => {
        const next = { ...old };
        delete next[column.id];
        return next;
      });
      return;
    }
    table.table.setColumnSizing((old: Record<string, number>) => ({
      ...old,
      [column.id]: action.width,
    }));
  }
</script>

<button
  type="button"
  {...svelteProps(handleProps)}
  onmousedown={startResize}
  ontouchstart={startResize}
  onclick={(event) => event.stopPropagation()}
  onkeydown={onKeyDown}
></button>

// packages/vue-table/src/components/Table/ResizeHandle.vue
<!--
  Pointer drag and keyboard, on one control.

  The drag is TanStack's own handler; the keyboard is core's `resizeKeyDown`, so
  the two cannot drift. It is a `role="separator"` with `aria-valuenow`, which is
  what makes the column width something a screen reader can report rather than
  something only a mouse can discover.
-->
<script setup lang="ts" generic="T extends RowData">
import { computed } from "vue";
import {
  getResizeHandleProps,
  resizeKeyDown,
  type RowData,
  type TableHeaderInstance,
} from "@ui-organized/table-core";
import { useTableContext } from "../../core/tableContext.js";
import { vueProps } from "../../core/props.js";

const props = defineProps<{ header: TableHeaderInstance<T> }>();
const table = useTableContext<T>();

const column = computed(() => props.header.column);
const bounds = computed(() => {
  const width = column.value.getSize();
  return {
    width,
    min: column.value.columnDef.minSize ?? 0,
    max: column.value.columnDef.maxSize ?? width,
  };
});

const handleProps = computed(() => {
  const headerDef = column.value.columnDef.header;
  return getResizeHandleProps({
    columnId: column.value.id,
    columnLabel: typeof headerDef === "string" ? headerDef : column.value.id,
    width: bounds.value.width,
    min: bounds.value.min,
    max: bounds.value.max,
    active: column.value.getIsResizing(),
  });
});

/** Stops the header's sort button from firing on the same press. */
function startResize(event: MouseEvent | TouchEvent) {
  event.stopPropagation();
  props.header.getResizeHandler()(event);
}

function onKeyDown(event: KeyboardEvent) {
  const action = resizeKeyDown(bounds.value, {
    key: event.key,
    shift: event.shiftKey,
    ctrl: event.ctrlKey,
    meta: event.metaKey,
  });
  if (action.type === "none") return;
  event.preventDefault();
  event.stopPropagation();
  if (action.type === "reset") {
    table.table.setColumnSizing((old: Record<string, number>) => {
      const next = { ...old };
      delete next[column.value.id];
      return next;
    });
    return;
  }
  table.table.setColumnSizing((old: Record<string, number>) => ({
    ...old,
    [column.value.id]: action.width,
  }));
}
</script>

<template>
  <button
    type="button"
    v-bind="vueProps(handleProps)"
    @mousedown="startResize"
    @touchstart="startResize"
    @click.stop
    @keydown="onKeyDown"
  />
</template>
