// packages/svelte-table/src/lib/components/Table/TableHeader.svelte
<script lang="ts">
  import { clsx } from "clsx";
  import { getHeaderRowProps } from "@ui-organized/table-core";
  import { getTable } from "../../core/tableContext.js";
  import { svelteProps } from "../../core/props.js";
  import TableHeadCell from "./TableHeadCell.svelte";

  let { class: className }: { class?: string } = $props();
  const table = getTable();
  const groups = $derived(table.table.getHeaderGroups());
  const rowProps = getHeaderRowProps();
</script>

<thead class={clsx("data-table__head", className)}>
  {#each groups as group (group.id)}
    <tr {...svelteProps(rowProps)}>
      {#each group.headers as header, index (header.id)}
        <TableHeadCell {header} {index} />
      {/each}
    </tr>
  {/each}
</thead>

// packages/vue-table/src/components/Table/TableHeader.vue
<script setup lang="ts">
import { computed } from "vue";
import { clsx } from "clsx";
import { getHeaderRowProps } from "@ui-organized/table-core";
import { useTableContext } from "../../core/tableContext.js";
import { vueProps } from "../../core/props.js";
import TableHeadCell from "./TableHeadCell.vue";

defineProps<{ class?: string }>();
const table = useTableContext();
const groups = computed(() => table.table.getHeaderGroups());
const rowProps = getHeaderRowProps();
</script>

<template>
  <thead :class="clsx('data-table__head', $props.class)">
    <tr v-for="group in groups" :key="group.id" v-bind="vueProps(rowProps)">
      <TableHeadCell
        v-for="(header, index) in group.headers"
        :key="header.id"
        :header="header"
        :index="index"
      />
    </tr>
  </thead>
</template>
