// packages/svelte-table/src/lib/components/Table/TableCell.svelte
<script lang="ts" generics="T extends RowData">
  import { FlexRender } from "@tanstack/svelte-table";
  import {
    alignOf,
    getCellProps,
    metaOf,
    stickyPositionOf,
    type RowData,
    type TableCellInstance,
    type TableEditContext,
    type TableInstance,
    type TableRowModel,
  } from "@ui-organized/table-core";
  import { getTable } from "../../core/tableContext.js";
  import { svelteProps } from "../../core/props.js";
  import CellEditor from "./CellEditor.svelte";

  let {
    cell,
    row,
    index,
    rowIndex,
    primary,
    focused,
    editContext,
  }: {
    cell: TableCellInstance<T>;
    row: TableRowModel<T>;
    index: number;
    rowIndex: number;
    primary: boolean;
    focused: boolean;
    editContext: TableEditContext<T> | null;
  } = $props();

  const table = getTable<T>();
  const column = $derived(cell.column);
  const meta = $derived(metaOf<T>(column.columnDef));
  const editing = $derived(editContext?.columnId === column.id ? editContext : null);
  const interactive = $derived(table.interactive);

  const cellProps = $derived(
    getCellProps({
      columnId: column.id,
      index,
      align: alignOf(column.columnDef),
      primary,
      sticky: stickyPositionOf(table.table as unknown as TableInstance<T>, column),
      focused,
      editing: Boolean(editing),
      invalid: Boolean(editing?.invalid),
      interactive,
    }),
  );

  const onFocus = () => {
    if (interactive) table.focus.setCursor({ row: rowIndex, col: index });
  };
  const onDoubleClick = () => {
    if (meta?.edit) table.edit.start(row, column.id);
  };
</script>

<!--
  The identifying column is a real row header, which is what makes a screen
  reader announce "Ada Lovelace, Role, Engineer" instead of just "Engineer".
  Svelte has no dynamic element by name, so the two tags are written out; the
  props and the content are shared.
-->
{#snippet content()}
  {#if editing}
    <CellEditor>
      {@const rendered = meta?.edit?.render(editing)}
      {#if typeof rendered === "function"}{@render rendered()}{:else}{rendered}{/if}
    </CellEditor>
  {:else}
    <FlexRender {cell} />
  {/if}
{/snippet}

{#if primary}
  <th
    {...svelteProps(cellProps)}
    data-cell={`${rowIndex}:${index}`}
    onfocus={onFocus}
    ondblclick={onDoubleClick}
  >
    {@render content()}
  </th>
{:else}
  <td
    {...svelteProps(cellProps)}
    data-cell={`${rowIndex}:${index}`}
    onfocus={onFocus}
    ondblclick={onDoubleClick}
  >
    {@render content()}
  </td>
{/if}

// packages/vue-table/src/components/Table/TableCell.vue
<script setup lang="ts" generic="T extends RowData">
import { computed } from "vue";
import { FlexRender } from "@tanstack/vue-table";
import {
  alignOf,
  getCellProps,
  metaOf,
  stickyPositionOf,
  type RowData,
  type TableCellInstance,
  type TableEditContext,
  type TableInstance,
  type TableRowModel,
} from "@ui-organized/table-core";
import { useTableContext } from "../../core/tableContext.js";
import { vueProps } from "../../core/props.js";
import CellEditor from "./CellEditor.vue";

const props = defineProps<{
  cell: TableCellInstance<T>;
  row: TableRowModel<T>;
  index: number;
  rowIndex: number;
  primary: boolean;
  focused: boolean;
  editContext: TableEditContext<T> | null;
}>();

const table = useTableContext<T>();
const column = computed(() => props.cell.column);
const meta = computed(() => metaOf<T>(column.value.columnDef));
const editing = computed(() =>
  props.editContext?.columnId === column.value.id ? props.editContext : null,
);
const interactive = computed(() => table.interactive.value);

const cellProps = computed(() =>
  getCellProps({
    columnId: column.value.id,
    index: props.index,
    align: alignOf(column.value.columnDef),
    primary: props.primary,
    sticky: stickyPositionOf(table.table as unknown as TableInstance<T>, column.value),
    focused: props.focused,
    editing: Boolean(editing.value),
    invalid: Boolean(editing.value?.invalid),
    interactive: interactive.value,
  }),
);

// The identifying column is a real row header, which is what makes a screen
// reader announce "Ada Lovelace, Role, Engineer" instead of just "Engineer".
const tag = computed(() => (props.primary ? "th" : "td"));

const onFocus = () => {
  if (interactive.value) table.focus.setCursor({ row: props.rowIndex, col: props.index });
};
const onDoubleClick = () => {
  if (meta.value?.edit) table.edit.start(props.row, column.value.id);
};
</script>

<template>
  <component
    :is="tag"
    v-bind="vueProps(cellProps)"
    :data-cell="`${rowIndex}:${index}`"
    @focus="onFocus"
    @dblclick="onDoubleClick"
  >
    <CellEditor v-if="editing">
      <component :is="() => meta?.edit?.render(editing!)" />
    </CellEditor>
    <FlexRender v-else :cell="cell" />
  </component>
</template>
