// packages/vue/src/components/Tooltip/Tooltip.vue
<!--
  Lightweight tooltip. Wrap a trigger and pass `content`.

  Like the Svelte package and unlike React, the trigger is always an Ark Trigger
  element rather than sometimes being projected onto the child:
  `isValidElement(children)` has no Vue equivalent, because a slot is opaque —
  there is no way to ask whether it renders exactly one element. Consumers who
  need the tooltip's behaviour projected onto their own element compose Ark's
  Trigger directly.
-->
<script setup lang="ts">
import { computed } from "vue";
import { Tooltip as ArkTooltip } from "@ark-ui/vue";
import { definedOnly } from "../../props.js";
import { useTooltipDelays } from "./delays.js";
import { toPlacement } from "../Popover/positioning.js";
import type { TooltipProps } from "./Tooltip.types.js";
import "@ui-organized/core/components/Tooltip/Tooltip.css";

const props = withDefaults(defineProps<TooltipProps>(), {
  side: "top",
  align: "center",
  sideOffset: 6,
});
const emit = defineEmits<{ "update:open": [open: boolean]; openChange: [open: boolean] }>();

const shared = useTooltipDelays();
const contentIsString = computed(() => typeof props.content === "string");
const rootProps = computed(() =>
  definedOnly({
    open: props.open,
    defaultOpen: props.defaultOpen,
    openDelay: props.delay ?? shared?.value.delay,
    closeDelay: props.closeDelay ?? shared?.value.closeDelay,
  }),
);
</script>

<template>
  <slot v-if="disabled" />
  <ArkTooltip.Root
    v-else
    v-bind="rootProps"
    :positioning="{ placement: toPlacement(side, align), gutter: sideOffset }"
    @open-change="
      (details) => {
        emit('update:open', details.open);
        emit('openChange', details.open);
      }
    "
  >
    <ArkTooltip.Trigger class="tooltip__trigger"><slot /></ArkTooltip.Trigger>
    <Teleport :to="container ?? 'body'">
      <ArkTooltip.Positioner class="tooltip__positioner">
        <ArkTooltip.Content class="tooltip__popup text-default-body-small">
          <template v-if="contentIsString">{{ content }}</template>
          <component :is="content" v-else />
        </ArkTooltip.Content>
      </ArkTooltip.Positioner>
    </Teleport>
  </ArkTooltip.Root>
</template>

// packages/svelte/src/lib/components/Tooltip/Tooltip.svelte
<!--
  Lightweight tooltip. Wrap a trigger and pass `content`.

  Unlike React, the trigger is always an Ark Trigger element rather than
  sometimes being projected onto the child: `React.isValidElement(children)` has
  no Svelte equivalent, because a snippet is opaque — there is no way to ask
  whether it renders exactly one element. Consumers who need the tooltip's
  behaviour projected onto their own element compose Ark's Trigger directly.
-->
<script lang="ts">
  import { Tooltip as ArkTooltip, Portal } from "@ark-ui/svelte";
  import { getTooltipDelays } from "./delays.svelte.js";
  import { toPlacement } from "../Popover/positioning.svelte.js";
  import type { TooltipProps } from "./Tooltip.types.js";
  import "@ui-organized/core/components/Tooltip/Tooltip.css";

  let {
    content,
    children,
    side = "top",
    align = "center",
    sideOffset = 6,
    delay,
    closeDelay,
    disabled,
    open = $bindable(),
    defaultOpen,
    onOpenChange,
    container,
  }: TooltipProps = $props();

  const shared = $derived(getTooltipDelays());
</script>

{#if disabled}
  {@render children()}
{:else}
  <ArkTooltip.Root
    bind:open
    {defaultOpen}
    onOpenChange={(details) => {
      open = details.open;
      onOpenChange?.(details.open);
    }}
    openDelay={delay ?? shared.delay}
    closeDelay={closeDelay ?? shared.closeDelay}
    positioning={{ placement: toPlacement(side, align), gutter: sideOffset }}
  >
    <ArkTooltip.Trigger class="tooltip__trigger">{@render children()}</ArkTooltip.Trigger>
    <Portal container={container ?? undefined}>
      <ArkTooltip.Positioner class="tooltip__positioner">
        <ArkTooltip.Content class="tooltip__popup text-default-body-small">
          {#if typeof content === "string"}{content}{:else}{@render content()}{/if}
        </ArkTooltip.Content>
      </ArkTooltip.Positioner>
    </Portal>
  </ArkTooltip.Root>
{/if}
