// packages/vue-table/src/components/TableToolbar/TableSearch.vue
<script setup lang="ts">
import { computed } from "vue";
import { clsx } from "clsx";
import { SearchInput } from "@ui-organized/vue";
import { useTableContext } from "../../core/tableContext.js";

const props = withDefaults(
  defineProps<{ placeholder?: string; label?: string; class?: string }>(),
  {
    placeholder: "Search",
  },
);
const table = useTableContext();
const name = computed(() => props.label ?? `Search ${table.label.value}`);
</script>

<template>
  <SearchInput
    :class="clsx('data-table__search', $props.class)"
    :size="table.size.value"
    :model-value="table.search.value"
    :placeholder="placeholder"
    :aria-label="name"
    @update:model-value="(value: string) => table.setSearch(value)"
  />
</template>

// packages/svelte-table/src/lib/components/TableToolbar/TableSearch.svelte
<script lang="ts">
  import { clsx } from "clsx";
  import { SearchInput } from "@ui-organized/svelte";
  import { getTable } from "../../core/tableContext.js";

  let {
    placeholder = "Search",
    label,
    class: className,
  }: { placeholder?: string; label?: string; class?: string } = $props();

  const table = getTable();
  const name = $derived(label ?? `Search ${table.label}`);
</script>

<SearchInput
  class={clsx("data-table__search", className)}
  size={table.size}
  value={table.search}
  {placeholder}
  aria-label={name}
  oninput={(event) => table.setSearch(event.currentTarget.value)}
  onClear={() => table.setSearch("")}
/>
