// packages/react/src/components/Listbox/Listbox.tsx
import { useMemo } from "react";
import { Listbox as ArkListbox, createListCollection } from "@ark-ui/react";
import { clsx } from "clsx";
import { Icon } from "../Icon/index.js";
import { CONTROL_ICON_SIZE, listboxStyles, type ControlSize } from "@ui-organized/core";
import type { ListboxProps, ListboxOption } from "./Listbox.types.js";
import "@ui-organized/core/components/Listbox/Listbox.css";

/** Options in declaration order, bucketed by `group`. Ungrouped options keep a
 *  `null` bucket so a partially grouped list still renders every option once,
 *  in the order it was given. */
function groupOptions(options: ListboxOption[]): [string | null, ListboxOption[]][] {
  const buckets = new Map<string | null, ListboxOption[]>();
  for (const option of options) {
    const key = option.group ?? null;
    const bucket = buckets.get(key);
    if (bucket) bucket.push(option);
    else buckets.set(key, [option]);
  }
  return [...buckets];
}

export function Listbox({
  options,
  label,
  value,
  defaultValue,
  onValueChange,
  selectionMode,
  size = "md",
  variant,
  emptyMessage = "No options",
  disabled,
  className,
}: ListboxProps) {
  const iconSize = CONTROL_ICON_SIZE[size as ControlSize];

  // Ark drives the list off a collection rather than children, the same way
  // Select does — `options` is the single source for both.
  const collection = useMemo(
    () =>
      createListCollection({
        items: options,
        itemToValue: (item) => item.value,
        itemToString: (item) => item.label,
        isItemDisabled: (item) => !!item.disabled,
      }),
    [options],
  );

  const groups = useMemo(() => groupOptions(options), [options]);

  return (
    <ArkListbox.Root
      className={clsx(listboxStyles({ size, variant }), className)}
      collection={collection}
      value={value}
      defaultValue={defaultValue}
      // Passed unconditionally, not as `onValueChange && (…)`. Ark's Root is
      // generic in the collection item, and a `fn | undefined` union at this
      // position defeats inference of that type parameter — the collection then
      // resolves to `ListCollection<unknown>` and stops matching.
      onValueChange={(details) => onValueChange?.(details.value)}
      selectionMode={selectionMode}
      disabled={disabled}
    >
      {label && <ArkListbox.Label className="listbox__label">{label}</ArkListbox.Label>}
      <ArkListbox.Content className="listbox__content">
        {groups.map(([group, groupItems]) => {
          const items = groupItems.map((item) => (
            <ArkListbox.Item key={item.value} item={item} className="listbox__item">
              <ArkListbox.ItemText className="listbox__item-text">{item.label}</ArkListbox.ItemText>
              <ArkListbox.ItemIndicator className="listbox__item-indicator">
                <Icon name="check" size={iconSize} />
              </ArkListbox.ItemIndicator>
            </ArkListbox.Item>
          ));

          // An ungrouped bucket must not be wrapped in an ItemGroup — that would
          // announce a group with no name to a screen reader.
          if (group == null) return items;

          return (
            <ArkListbox.ItemGroup key={group} className="listbox__group">
              <ArkListbox.ItemGroupLabel className="listbox__group-label">
                {group}
              </ArkListbox.ItemGroupLabel>
              {items}
            </ArkListbox.ItemGroup>
          );
        })}
        {/* A `listbox` must own `option` or `group` children, and with no items
            it had neither — axe rates that critical, because a screen reader
            entering the list is told it is a listbox and then finds nothing in
            it. A disabled option is the conventional answer: the list is never
            childless, and what the user hears ("No results, dimmed") is true.

            Rendered directly rather than through `ArkListbox.Empty`, which
            hard-codes `role="presentation"` and ignores a `role` prop — the
            element it produces is exactly the child the rule rejects. */}
        {options.length === 0 && (
          <div role="option" aria-disabled="true" aria-selected="false" className="listbox__empty">
            {emptyMessage}
          </div>
        )}
      </ArkListbox.Content>
    </ArkListbox.Root>
  );
}

// packages/svelte/src/lib/components/Listbox/Listbox.svelte
<!--
  A standing list of options — the always-visible sibling of Select. Nothing is
  portalled here, so the whole component is one subtree.
-->
<script lang="ts">
  import { Listbox as ArkListbox, createListCollection } from "@ark-ui/svelte";
  import { clsx } from "clsx";
  import { CONTROL_ICON_SIZE, listboxStyles, type ControlSize } from "@ui-organized/core";
  import Icon from "../Icon/Icon.svelte";
  import type { ListboxProps, ListboxOption } from "./Listbox.types.js";
  import "@ui-organized/core/components/Listbox/Listbox.css";

  let {
    options,
    label,
    value = $bindable(),
    defaultValue,
    onValueChange,
    selectionMode,
    size = "md",
    variant,
    emptyMessage = "No options",
    disabled,
    class: className,
  }: ListboxProps = $props();

  const iconSize = $derived(CONTROL_ICON_SIZE[size as ControlSize]);

  // Ark drives the list off a collection rather than children, the same way
  // Select does — `options` is the single source for both.
  const collection = $derived(
    createListCollection({
      items: options,
      itemToValue: (item) => item.value,
      itemToString: (item) => item.label,
      isItemDisabled: (item) => !!item.disabled,
    }),
  );

  /**
   * Options in declaration order, bucketed by `group`. Ungrouped options keep a
   * `null` bucket so a partially grouped list still renders every option once,
   * in the order it was given.
   */
  const groups = $derived.by<[string | null, ListboxOption[]][]>(() => {
    const buckets = new Map<string | null, ListboxOption[]>();
    for (const option of options) {
      const key = option.group ?? null;
      const bucket = buckets.get(key);
      if (bucket) bucket.push(option);
      else buckets.set(key, [option]);
    }
    return [...buckets];
  });
</script>

<!--
  One bucket of options, rendered without a wrapper of its own. A snippet rather
  than the markup twice over, because the grouped and ungrouped branches render
  identical items and writing it twice is how the two drift.
-->
{#snippet bucket(items: ListboxOption[])}
  {#each items as item (item.value)}
    <ArkListbox.Item {item} class="listbox__item">
      <!--
        ── Why the element is pinned ─────────────────────────────────────────

        `@ark-ui/svelte` is on 5.24 while React is on 5.37, and Ark changed this
        part's default element in between: a `<span>` here, a `<div>` there. One
        stylesheet styles all three libraries, so the tag it is written against
        cannot be whichever Ark version a package happens to install.

        The difference is invisible *today* — `.listbox__item` is a flex row, and
        a flex item is blockified whatever its display was, so the span's
        `overflow: hidden` and its ellipsis still work. That is the trap rather
        than the reassurance: the day the row stops being a flex container the
        truncation silently stops working in one library only.
      -->
      <ArkListbox.ItemText>
        {#snippet asChild(project)}
          <div {...project()} class="listbox__item-text">{item.label}</div>
        {/snippet}
      </ArkListbox.ItemText>
      <ArkListbox.ItemIndicator class="listbox__item-indicator">
        <Icon name="check" size={iconSize} />
      </ArkListbox.ItemIndicator>
    </ArkListbox.Item>
  {/each}
{/snippet}

<ArkListbox.Root
  class={clsx(listboxStyles({ size, variant }), className)}
  {collection}
  {value}
  {defaultValue}
  onValueChange={(details) => {
    value = details.value;
    onValueChange?.(details.value);
  }}
  {selectionMode}
  {disabled}
>
  {#if label}
    <ArkListbox.Label class="listbox__label">{label}</ArkListbox.Label>
  {/if}
  <ArkListbox.Content class="listbox__content">
    {#each groups as [group, groupItems] (group ?? "")}
      {#if group != null}
        <ArkListbox.ItemGroup class="listbox__group">
          <ArkListbox.ItemGroupLabel class="listbox__group-label">
            {group}
          </ArkListbox.ItemGroupLabel>
          {@render bucket(groupItems)}
        </ArkListbox.ItemGroup>
      {:else}
        <!--
          An ungrouped bucket must not be wrapped in an ItemGroup — that would
          announce a group with no name to a screen reader.
        -->
        {@render bucket(groupItems)}
      {/if}
    {/each}
    <!-- A `listbox` must own `option` or `group` children, and with no items it
         had neither — axe rates that critical, because a screen reader entering
         the list is told it is a listbox and then finds nothing in it. A
         disabled option is the conventional answer: the list is never childless,
         and what the user hears ("No results, dimmed") is true.

         Written out rather than using `ArkListbox.Empty`, which hard-codes
         `role="presentation"` and ignores a `role` prop — the element it
         produces is exactly the child the rule rejects. Same reasoning, and same
         markup, as the React library. -->
    {#if options.length === 0}
      <div role="option" aria-disabled="true" aria-selected="false" class="listbox__empty">
        {emptyMessage}
      </div>
    {/if}
  </ArkListbox.Content>
</ArkListbox.Root>
