// packages/react/src/components/Combobox/Combobox.tsx
import { useMemo, useState } from "react";
import {
  Combobox as ArkCombobox,
  Field,
  Portal,
  createListCollection,
  useFilter,
} from "@ark-ui/react";
import { clsx } from "clsx";
import { CONTROL_ICON_SIZE, comboboxFieldStyles } from "@ui-organized/core";
import { Icon } from "../Icon/index.js";
import { FieldError } from "../FieldError/index.js";
import type { ComboboxProps } from "./Combobox.types.js";
import "@ui-organized/core/components/Combobox/Combobox.css";
import { useContainedPositioning, useOverlayPortal } from "../../preview/useOverlayPortal.js";

// Module-level so `useFilter`'s memo key is stable (it keys on the props object
// identity); otherwise `contains` — and the derived collection — would churn
// every render.
const FILTER_OPTIONS = { sensitivity: "base" } as const;

export function Combobox({
  options,
  value,
  defaultValue,
  onValueChange,
  open,
  defaultOpen,
  onOpenChange,
  placeholder,
  label,
  helperText,
  error,
  size,
  disabled,
  name,
  required,
  className,
  emptyMessage = "No results found.",
  portalContainer,
}: ComboboxProps) {
  const isInvalid = !!error;
  const errorMessage = typeof error === "string" ? error : undefined;
  const portal = useOverlayPortal();
  const containedPositioning = useContainedPositioning();

  // Ark doesn't filter for us (Base UI did): mirror the input text and rebuild
  // the collection from the matching options. Rendering items from
  // `collection.items` keeps the rendered list and the machine's collection in
  // sync.
  const { contains } = useFilter(FILTER_OPTIONS);
  const [query, setQuery] = useState("");
  const collection = useMemo(() => {
    const items = query.trim().length
      ? options.filter((o) => contains(o.label, query))
      : options;
    return createListCollection({
      items,
      itemToValue: (o) => o.value,
      itemToString: (o) => o.label,
      isItemDisabled: (o) => !!o.disabled,
    });
  }, [options, query, contains]);

  return (
    <Field.Root
      className={clsx(comboboxFieldStyles({ size }), className)}
      invalid={isInvalid}
      disabled={disabled}
    >
      {/* Ark Combobox.Root renders a wrapping <div>; `display:contents` keeps the
          label / control / helper as direct flex children of the field. */}
      <ArkCombobox.Root
        className="combobox-field__root"
        collection={collection}
        value={value != null ? [value] : undefined}
        defaultValue={defaultValue != null ? [defaultValue] : undefined}
        onValueChange={
          onValueChange ? (details) => onValueChange(details.value[0] ?? "") : undefined
        }
        onInputValueChange={(details) => setQuery(details.inputValue)}
        open={open}
        defaultOpen={defaultOpen}
        onOpenChange={onOpenChange ? (details) => onOpenChange(details.open) : undefined}
        invalid={isInvalid}
        disabled={disabled}
        name={name}
        required={required}
        positioning={{ placement: "bottom-start", gutter: 4, strategy: "fixed", ...containedPositioning }}
      >
        {label && (
          <ArkCombobox.Label className="field__label">
            {label}
            {required && <span className="field__required" aria-hidden="true" />}
          </ArkCombobox.Label>
        )}
        <ArkCombobox.Control className="combobox-field__control">
          <ArkCombobox.Input
            className="field__control combobox-field__input"
            placeholder={placeholder}
          />
          <ArkCombobox.Trigger className="combobox-field__trigger" aria-label="Toggle options">
            <Icon name="chevron-down" size={CONTROL_ICON_SIZE[size ?? "md"]} />
          </ArkCombobox.Trigger>
        </ArkCombobox.Control>
        {/* An explicitly-passed container still wins over the preview context. */}
        <Portal {...(portalContainer ? { container: { current: portalContainer } } : portal)}>
          <ArkCombobox.Positioner className="combobox-positioner">
            <ArkCombobox.Content className="combobox-popup">
              <ArkCombobox.Empty className="combobox-popup__empty text-default-body-medium">{emptyMessage}</ArkCombobox.Empty>
              {/* Items sit directly in Content, which is itself the listbox —
                  Combobox.List is a second labelled wrapper for the
                  non-composite mode, and in between it reads as a child of the
                  listbox that isn't an option. */}
              {collection.items.map((item) => (
                <ArkCombobox.Item key={item.value} item={item} className="combobox-popup__item text-default-body-large">
                  <span className="combobox-popup__item-label">{item.label}</span>
                  <ArkCombobox.ItemIndicator className="combobox-popup__item-indicator">
                    <Icon name="check" size={CONTROL_ICON_SIZE[size ?? "md"]} />
                  </ArkCombobox.ItemIndicator>
                </ArkCombobox.Item>
              ))}
            </ArkCombobox.Content>
          </ArkCombobox.Positioner>
        </Portal>
      </ArkCombobox.Root>
      {helperText && !isInvalid && (
        <Field.HelperText className="field__description">{helperText}</Field.HelperText>
      )}
      {isInvalid && errorMessage && (
        <Field.ErrorText asChild>
          <FieldError>{errorMessage}</FieldError>
        </Field.ErrorText>
      )}
    </Field.Root>
  );
}

// packages/svelte/src/lib/components/Combobox/Combobox.svelte
<script lang="ts">
  import {
    Combobox as ArkCombobox, Field, Portal, createListCollection, useFilter,
  } from "@ark-ui/svelte";
  import { clsx } from "clsx";
  import { CONTROL_ICON_SIZE, comboboxFieldStyles } from "@ui-organized/core";
  import Icon from "../Icon/Icon.svelte";
  import FieldError from "../FieldError/FieldError.svelte";
  import type { ComboboxProps } from "./Combobox.types.js";
  import "@ui-organized/core/components/Combobox/Combobox.css";

  let {
    options,
    value = $bindable(),
    defaultValue,
    onValueChange,
    open = $bindable(),
    defaultOpen,
    onOpenChange,
    placeholder,
    label,
    helperText,
    error,
    size,
    disabled,
    name,
    required,
    class: className,
    emptyMessage = "No results found.",
    portalContainer,
  }: ComboboxProps = $props();

  const isInvalid = $derived(!!error);
  const errorMessage = $derived(typeof error === "string" ? error : undefined);
  const iconSize = $derived(CONTROL_ICON_SIZE[size ?? "md"]);

  // Ark does not filter for us: mirror the input text and rebuild the collection
  // from the matching options. Rendering items from `collection.items` keeps the
  // rendered list and the machine's collection in step.
  //
  // React memoises `useFilter`'s options object at module scope so the memo key
  // stays stable. Svelte needs no such care — `$derived` tracks the values it
  // reads rather than an argument identity — so the options are inline here.
  const filter = useFilter({ sensitivity: "base" });
  let query = $state("");

  const collection = $derived(
    createListCollection({
      items: query.trim().length
        ? options.filter((o) => filter().contains(o.label, query))
        : options,
      itemToValue: (o) => o.value,
      itemToString: (o) => o.label,
      isItemDisabled: (o) => !!o.disabled,
    }),
  );
</script>

<Field.Root
  class={clsx(comboboxFieldStyles({ size }), className)}
  invalid={isInvalid}
  {disabled}
>
  <!--
    Ark Combobox.Root renders a wrapping <div>; `display:contents` keeps the
    label, control and helper as direct flex children of the field.
  -->
  <ArkCombobox.Root
    class="combobox-field__root"
    {collection}
    value={value != null ? [value] : undefined}
    defaultValue={defaultValue != null ? [defaultValue] : undefined}
    onValueChange={(details) => {
      value = details.value[0] ?? "";
      onValueChange?.(details.value[0] ?? "");
    }}
    onInputValueChange={(details) => (query = details.inputValue)}
    {open}
    {defaultOpen}
    onOpenChange={(details) => {
      open = details.open;
      onOpenChange?.(details.open);
    }}
    invalid={isInvalid}
    {disabled}
    {name}
    {required}
    positioning={{ placement: "bottom-start", gutter: 4, strategy: "fixed" }}
  >
    {#if label}
      <ArkCombobox.Label class="field__label">
        {label}
        {#if required}<span class="field__required" aria-hidden="true"></span>{/if}
      </ArkCombobox.Label>
    {/if}
    <ArkCombobox.Control class="combobox-field__control">
      <!--
        `aria-describedby` is passed in by hand because Ark Svelte's
        `Combobox.Input` does not read the Field context, where Ark React's does:

            // @ark-ui/react/dist/components/combobox/combobox-input.js
            const field = useFieldContext();
            return jsx(ark.input, { "aria-describedby": field?.ariaDescribedby, ...mergedProps });

        Without this the helper text is rendered but associated with nothing, so
        a screen reader never announces it — the field silently loses half its
        description. This is a wrapper gap, not a machine one: both zag versions
        are identical here, and the combobox machine never sets the attribute
        itself, which is exactly why React needs the Field fallback too.

        Six Ark Svelte parts have this gap. This one is pinned by the browser
        gate's `Combobox / helper text` scenario; the others are recorded in the
        roadmap because nothing renders them under a Field yet.

        Delete once Ark Svelte's part reads the context — the merge order makes
        that safe either way, since the machine supplies no competing value.
      -->
      <Field.Context>
        {#snippet render(field)}
          <ArkCombobox.Input
            class="field__control combobox-field__input"
            {placeholder}
            aria-describedby={field()?.ariaDescribedby}
          />
        {/snippet}
      </Field.Context>
      <ArkCombobox.Trigger class="combobox-field__trigger" aria-label="Toggle options">
        <Icon name="chevron-down" size={iconSize} />
      </ArkCombobox.Trigger>
    </ArkCombobox.Control>
    <Portal container={portalContainer ?? undefined}>
      <ArkCombobox.Positioner class="combobox-positioner">
        <ArkCombobox.Content class="combobox-popup">
          <ArkCombobox.Empty class="combobox-popup__empty text-default-body-medium">
            {emptyMessage}
          </ArkCombobox.Empty>
          <!--
            Items sit directly in Content, which is itself the listbox —
            Combobox.List is a second labelled wrapper for the non-composite
            mode, and in between it reads as a child of the listbox that isn't an
            option.
          -->
          {#each collection.items as item (item.value)}
            <ArkCombobox.Item {item} class="combobox-popup__item text-default-body-large">
              <span class="combobox-popup__item-label">{item.label}</span>
              <ArkCombobox.ItemIndicator class="combobox-popup__item-indicator">
                <Icon name="check" size={iconSize} />
              </ArkCombobox.ItemIndicator>
            </ArkCombobox.Item>
          {/each}
        </ArkCombobox.Content>
      </ArkCombobox.Positioner>
    </Portal>
  </ArkCombobox.Root>
  {#if helperText && !isInvalid}
    <Field.HelperText class="field__description">{helperText}</Field.HelperText>
  {/if}
  {#if isInvalid && errorMessage}
    <Field.ErrorText>
      {#snippet asChild(props)}
        <FieldError {...props()} message={errorMessage} />
      {/snippet}
    </Field.ErrorText>
  {/if}
</Field.Root>
