// tooling/parity/src/fixtures/FloatingPanelFixture.svelte
<script lang="ts">
  import {
    FloatingPanel, FloatingPanelTrigger, FloatingPanelContent, FloatingPanelHeader,
    FloatingPanelTitle, FloatingPanelBody, FloatingPanelClose,
  } from "@ui-organized/svelte";

  /**
   * `triggerClass` is separate from `triggerProps` because the gate rewrites
   * `className` to `class` for this side only at the top level. A nested
   * `triggerProps.className` would arrive here unrenamed and be forwarded to the
   * DOM as an unknown attribute, so the dialect is spelled out per framework and
   * the value stays in the case.
   */
  let {
    triggerProps = {},
    triggerClass,
    contentProps = {},
    bodyClose,
    ...props
  }: Record<string, any> = $props();
</script>

<FloatingPanel {...props}>
  <FloatingPanelTrigger class={triggerClass} {...triggerProps}>Open</FloatingPanelTrigger>
  <FloatingPanelContent {...contentProps}>
    <FloatingPanelHeader>
      <FloatingPanelTitle>Title</FloatingPanelTitle>
      <FloatingPanelClose />
    </FloatingPanelHeader>
    <FloatingPanelBody>
      Body
      {#if bodyClose}<FloatingPanelClose>Done</FloatingPanelClose>{/if}
    </FloatingPanelBody>
  </FloatingPanelContent>
</FloatingPanel>

// tooling/parity/src/fixtures/vue/FloatingPanelFixture.vue
<script setup lang="ts">
import {
  FloatingPanel,
  FloatingPanelTrigger,
  FloatingPanelContent,
  FloatingPanelHeader,
  FloatingPanelTitle,
  FloatingPanelBody,
  FloatingPanelClose,
} from "@ui-organized/vue";

/** `triggerClass` rather than a nested className — see FloatingPanelFixture.svelte. */
defineProps<{
  triggerProps?: Record<string, unknown>;
  triggerClass?: string;
  contentProps?: Record<string, unknown>;
  bodyClose?: boolean;
}>();
</script>

<template>
  <FloatingPanel v-bind="$attrs">
    <FloatingPanelTrigger :class="triggerClass" v-bind="triggerProps">Open</FloatingPanelTrigger>
    <FloatingPanelContent v-bind="contentProps">
      <FloatingPanelHeader>
        <FloatingPanelTitle>Title</FloatingPanelTitle>
        <FloatingPanelClose />
      </FloatingPanelHeader>
      <FloatingPanelBody>
        Body
        <FloatingPanelClose v-if="bodyClose">Done</FloatingPanelClose>
      </FloatingPanelBody>
    </FloatingPanelContent>
  </FloatingPanel>
</template>
