// packages/react/src/components/Skeleton/Skeleton.tsx
import { clsx } from "clsx";
import { skeletonStyles } from "@ui-organized/core";
import type { SkeletonProps } from "./Skeleton.types.js";
import "@ui-organized/core/components/Skeleton/Skeleton.css";

/** A number is treated as pixels; strings pass through as-is. */
function toCssSize(value?: number | string): string | undefined {
  if (value == null) return undefined;
  return typeof value === "number" ? `${value}px` : value;
}

/**
 * Loading placeholder. Renders a shimmering block sized to the eventual content.
 * For multi-line text, pass `lines` to render a stack with a shortened last row.
 */
export function Skeleton({
  variant = "text",
  width,
  height,
  lines = 1,
  animated = true,
  className,
  style,
  ...props
}: SkeletonProps) {
  const w = toCssSize(width);
  const h = toCssSize(height);

  if (variant === "text" && lines > 1) {
    return (
      <div className={clsx("skeleton-group", className)} style={style} aria-hidden="true" {...props}>
        {Array.from({ length: lines }).map((_, i) => (
          <span
            key={i}
            className={skeletonStyles({ variant, animated })}
            style={{ width: i === lines - 1 ? "60%" : w ?? "100%", height: h }}
          />
        ))}
      </div>
    );
  }

  return (
    <span
      className={clsx(skeletonStyles({ variant, animated }), className)}
      style={{ width: w, height: h, ...style }}
      aria-hidden="true"
      {...props}
    />
  );
}

// packages/vue/src/components/Skeleton/Skeleton.vue
<!--
  Loading placeholder. Renders a shimmering block sized to the eventual content.
  For multi-line text, pass `lines` to render a stack with a shortened last row.
-->
<script setup lang="ts">
import { computed, useAttrs } from "vue";
import { clsx } from "clsx";
import { skeletonStyles } from "@ui-organized/core";
import type { SkeletonProps } from "./Skeleton.types.js";
import "@ui-organized/core/components/Skeleton/Skeleton.css";

defineOptions({ inheritAttrs: false });
const props = withDefaults(defineProps<SkeletonProps>(), {
  variant: "text",
  lines: 1,
  animated: true,
});
const attrs = useAttrs();

/** A number is treated as pixels; strings pass through as-is. */
const toCssSize = (value?: number | string): string | undefined =>
  value == null ? undefined : typeof value === "number" ? `${value}px` : value;

const w = computed(() => toCssSize(props.width));
const h = computed(() => toCssSize(props.height));
const isStack = computed(() => props.variant === "text" && props.lines > 1);
const itemClass = computed(() =>
  skeletonStyles({ variant: props.variant, animated: props.animated }),
);
const soloClass = computed(() => clsx(itemClass.value, attrs.class as string));
const stackClass = computed(() => clsx("skeleton-group", attrs.class as string));

const lineStyle = (i: number) => ({
  width: i === props.lines - 1 ? "60%" : (w.value ?? "100%"),
  height: h.value,
});
</script>

<template>
  <div
    v-if="isStack"
    :class="stackClass"
    aria-hidden="true"
    v-bind="{ ...$attrs, class: undefined }"
  >
    <span v-for="i in lines" :key="i" :class="itemClass" :style="lineStyle(i - 1)" />
  </div>
  <span
    v-else
    :class="soloClass"
    :style="{ width: w, height: h }"
    aria-hidden="true"
    v-bind="{ ...$attrs, class: undefined }"
  />
</template>
