// packages/vue/src/components/Menu/MenuContent.vue
<!-- Teleported, positioned surface holding the menu items. -->
<script setup lang="ts">
import { watchEffect } from "vue";
import { Menu as ArkMenu } from "@ark-ui/vue";
import { useAnchoredPositioning, toPlacement } from "../Popover/positioning.js";
import type { MenuContentProps } from "./Menu.types.js";

defineOptions({ inheritAttrs: false });
const props = withDefaults(defineProps<MenuContentProps>(), {
  side: "bottom",
  align: "start",
  sideOffset: 4,
});

const positioning = useAnchoredPositioning();
watchEffect(() => {
  if (!positioning) return;
  positioning.value = {
    placement: toPlacement(props.side, props.align),
    gutter: props.sideOffset,
    offset: props.alignOffset != null ? { crossAxis: props.alignOffset } : undefined,
  };
});
</script>

<template>
  <Teleport :to="container ?? 'body'">
    <ArkMenu.Positioner class="menu__positioner">
      <ArkMenu.Content class="menu__popup" v-bind="$attrs"><slot /></ArkMenu.Content>
    </ArkMenu.Positioner>
  </Teleport>
</template>

// packages/svelte/src/lib/components/Menu/MenuContent.svelte
<!-- Portalled, positioned surface holding the menu items. -->
<script lang="ts">
  import { Menu as ArkMenu, Portal } from "@ark-ui/svelte";
  import { clsx } from "clsx";
  import { setAnchoredPositioning, toPlacement } from "../Popover/positioning.svelte.js";
  import type { MenuContentProps } from "./Menu.types.js";

  let {
    side = "bottom",
    align = "start",
    sideOffset = 4,
    alignOffset,
    container,
    class: className,
    children,
    ...contentProps
  }: MenuContentProps = $props();

  setAnchoredPositioning(() => ({
    placement: toPlacement(side, align),
    gutter: sideOffset,
    offset: alignOffset != null ? { crossAxis: alignOffset } : undefined,
  }));
</script>

<Portal container={container ?? undefined}>
  <ArkMenu.Positioner class="menu__positioner">
    <ArkMenu.Content class={clsx("menu__popup", className)} {...contentProps}>
      {@render children?.()}
    </ArkMenu.Content>
  </ArkMenu.Positioner>
</Portal>
