// packages/svelte/src/lib/components/DateField/DatePopover.svelte
<!--
  The portal + positioner + popup surface shared by the date pickers. Must be
  rendered inside a controlled `ArkPopover.Root` (which owns the anchor
  positioning and the initial focus); the trigger lives in the field.
-->
<script lang="ts">
  import { Popover as ArkPopover, Portal } from "@ark-ui/svelte";
  import type { DatePopoverProps } from "./DatePopover.types.js";
  import "@ui-organized/core/components/DateField/DatePopover.css";

  let { container, label, children }: DatePopoverProps = $props();
</script>

<Portal container={container ?? undefined}>
  <!--
    The positioner class must stay a plain string literal: the overlay-stacking
    test scans for it, and stacking is declared on the popup rather than here
    because zag writes an inline z-index onto the positioner and reads it from
    the popup's rule.
  -->
  <ArkPopover.Positioner class="date-popover-positioner">
    <ArkPopover.Content class="date-popover" aria-label={label}>
      {@render children?.()}
    </ArkPopover.Content>
  </ArkPopover.Positioner>
</Portal>

// packages/react/src/components/DateField/DatePopover.tsx
import { Popover as ArkPopover, Portal } from "@ark-ui/react";
import type { ReactNode, RefObject } from "react";
import "./DatePopover.css";

export interface DatePopoverProps {
  /** Optional container for the portal (defaults to document.body). */
  container?: HTMLElement | null;
  children: ReactNode;
}

/**
 * Build the Ark popover positioning that anchors the calendar to a field/row
 * element (rather than the small trigger button) and floats it below, left-aligned.
 * Set on the controlled `Popover.Root` alongside `initialFocusEl`.
 */
export function datePopoverPositioning(anchorRef: RefObject<HTMLElement | null>) {
  return {
    placement: "bottom-start" as const,
    gutter: 6,
    strategy: "fixed" as const,
    getAnchorRect: () => {
      const r = anchorRef.current?.getBoundingClientRect();
      return r ? { x: r.x, y: r.y, width: r.width, height: r.height } : null;
    },
  };
}

/**
 * The portal + positioner + popup surface shared by the date pickers. Must be
 * rendered inside a controlled `ArkPopover.Root` (which owns the anchor
 * positioning and initial focus); the trigger lives in the field.
 */
export function DatePopover({ container, children }: DatePopoverProps) {
  return (
    <Portal container={container ? { current: container } : undefined}>
      <ArkPopover.Positioner className="date-popover-positioner">
        <ArkPopover.Content className="date-popover">{children}</ArkPopover.Content>
      </ArkPopover.Positioner>
    </Portal>
  );
}
